### ISSUE TITLE
Is this paper style?

### ISSUE THREAD

**Issue by libook** [snwh/paper-gtk-theme#100]
I love this theme!
But when I updated the theme today,
something was different.
And I think that this is not match with 'paper style'.
Please look at red arrows on the picture.
In my opinion, 'paper style' is let elements 'look like paper'.
Every elements looks well, but these.

![2015-03-1](https://cloud.githubusercontent.com/assets/3395610/6592149/9dfa1518-c804-11e4-83e5-3a63c11eb3f1.png)

Is there something wrong when I update this theme?
Or this really is 'paper style'?

**Comment by region51** [comment]
gnome-shell preview
http://snwh.org/paper/gnome-shell-theme/

**Comment by snwh** [comment]
I think there's a bug. What version of GNOME Shell are you using?

**Comment by sqrt** [comment]
It's the same for me on Fedora 21 using GNOME Shell 3.14.3.

Also, many other elements now look like default Adwaita Shell theme (e.g. the "Close" button in the ALT+F2 run dialog). This has been introduced in commit 05fdc3d2d "Rewrote GNOME Shell theme".

**Comment by snwh** [comment]
The default theme needs to be completely overridden otherwise elements will show through. I'll have to test it out to fix these bugs

**Comment by libook** [comment]
Thanks for @snwh 's reply,
I am using GNOME Shell 3.14.3.
I upgraded the theme today, and it became like this:
![2015-03-12](https://cloud.githubusercontent.com/assets/3395610/6611152/a515cbf4-c8a3-11e4-9f56-6ab1756bc0f3.png)
Seem like elements returned to normal, but two.

**Comment by snwh** [comment]
Fixed

**Comment by WoefulDerelict** [comment]
It does appear to be fixed. Just synced and the spacing looks fine on my Arch box with 3.14.2

**Comment by snwh** [comment]
I spun up a VM just for you all to test & bug-fix the theme
