### ISSUE TITLE
Date and Clock in Menu Bar is missing

### ISSUE THREAD

**Issue by nscornia** [snwh/paper-gtk-theme#102]
After do an update today the date and clock that is normally in my menu bar is gone. Going into settings show that they should still be in there. 
![missingdateandclock](https://cloud.githubusercontent.com/assets/5322825/6622503/a13f3174-c8a2-11e4-913a-1dc53d6e8bb0.png)
![settings](https://cloud.githubusercontent.com/assets/5322825/6622525/b453b0a0-c8a2-11e4-8e61-1f2e54936817.png)

**Comment by nscornia** [comment]
This is on "Ubuntu 14.04.2 LTS" using Unity

**Comment by snwh** [comment]
Confirm this is Paper-specific. Test with a different theme.

**Comment by nscornia** [comment]
You are right, not Paper related, sorry for the trouble

**Comment by snwh** [comment]
No worries.
