### ISSUE TITLE
Different HeaderBar colors for Web apps

### ISSUE THREAD

**Issue by sqrt** [snwh/paper-gtk-theme#104]
In Fedora, it's possible to install Web apps based on Epiphany's kiosk mode using GNOME Software ([rhbz#710112](https://bugzilla.gnome.org/show_bug.cgi?id=710112). These install as desktop files in ``~/.local/share/applications/epiphany-*.desktop``, which include this line:

    StartupWMClass=epiphany-googlemaps.desktop-${HASHVALUE}

The WM_CLASS can be queried using:

    $ xprop WM_CLASS
    WM_CLASS(STRING) = "epiphany-googlemaps.desktop-${HASHVALUE}", "epiphany-googlemaps.desktop-${HASHVALUE}"

I don't know if it's possible, but it would be great if the ``WM_CLASS`` could be used for styling the header bars with indivual colors based on the Web app, similar to [Lollipops recent apps view](https://www.block8.co.uk/blog/is-your-website-ready-for-android-lollipop):

![3b174a200f0939305e9b92d34a4837ff](https://cloud.githubusercontent.com/assets/303458/6637720/3ecbd646-c97e-11e4-8f0f-03ab36e7b773.jpg)

More information:
https://blogs.gnome.org/xan/2011/08/31/web-application-mode-in-gnome-3-2/
https://bugzilla.gnome.org/show_bug.cgi?id=710112
https://askubuntu.com/questions/367396/what-represent-the-startupwmclass-field-of-a-desktop-file

**Comment by snwh** [comment]
Yeah, that's impossible. The webapp's headerbar is still Web/Epiphany's. 

The multi-coloured headerbars in Paper is simply due to some significant hackery & poking around that I've done.

**Comment by dehen** [comment]
So how are you actually finding the element names for the headerbars on a per-app basis? Havf you been digging in the code? I was trying to change nuvola3's headerbar color this morning and I thought xprop would help me. I was veryvery wrong.

**Comment by snwh** [comment]
Recolouring is sometimes possible based whether or not an application has a unique top-level Gtk class/name

**Comment by snwh** [comment]
Closing this
