### ISSUE TITLE
Nautilus' height changes when path bar's focused

### ISSUE THREAD

**Issue by superscript18** [snwh/paper-gtk-theme#108]
When you press Ctrl+L in Nautilus, the height of the window's header bar changes.

It seems like you could just add a little extra padding to the path entry feild top and bottom.

**Comment by snwh** [comment]
Fixed

**Comment by superscript18** [comment]
Hmm... now it's the opposite problem: too much space. When I press Ctrl+L, height increases by a few pixels.
