### ISSUE TITLE
New Menu Styles Are Impossible To See (Blend Into Windows)

### ISSUE THREAD

**Issue by rockon999** [snwh/paper-gtk-theme#109]
The gnome-shell theme blends into the unfocused windows... I'm not sure if this was intentional but it is rather hard to use. 

Gnome 3.14.3:

![screenshot from 2015-03-14 22 40 52](https://cloud.githubusercontent.com/assets/2943271/6654572/3d1846ea-ca9b-11e4-8e4d-763461887eca.png)
![Uploading Screenshot from 2015-03-14 22:40:54.png . . .]()
![screenshot from 2015-03-14 22 40 56](https://cloud.githubusercontent.com/assets/2943271/6654575/3d19c9a2-ca9b-11e4-9a1d-4d302d941aa1.png)
![screenshot from 2015-03-14 22 40 58](https://cloud.githubusercontent.com/assets/2943271/6654576/3d1a827a-ca9b-11e4-848d-efc471678e03.png)
![screenshot from 2015-03-14 22 40 59](https://cloud.githubusercontent.com/assets/2943271/6654574/3d19b67e-ca9b-11e4-8b2a-1c6aed83dd52.png)
![screenshot from 2015-03-14 22 41 04](https://cloud.githubusercontent.com/assets/2943271/6654578/3d2792e4-ca9b-11e4-8305-67bcccc9291b.png)
![screenshot from 2015-03-14 22 41 06](https://cloud.githubusercontent.com/assets/2943271/6654577/3d272c28-ca9b-11e4-92fc-33b5790a3a94.png)
![screenshot from 2015-03-14 22 41 07](https://cloud.githubusercontent.com/assets/2943271/6654579/3d27d7d6-ca9b-11e4-92fc-6affa3e446d8.png)

**Comment by snwh** [comment]
Your backups failing too I see.

**Comment by rockon999** [comment]
My local server was shutdown :P

**Comment by snwh** [comment]
Fixed as far as I can see.
