### ISSUE TITLE
Totem controls size

### ISSUE THREAD

**Issue by Twixx** [snwh/paper-gtk-theme#110]
In totem video player, controls are resized on hover.
Normal :
![normal](https://cloud.githubusercontent.com/assets/11486364/6655863/f18b49f8-cb11-11e4-9c76-318229dd75ce.png)
Hover play/pause :
![hover1](https://cloud.githubusercontent.com/assets/11486364/6655861/f0e09d82-cb11-11e4-835c-ae91e82a0ddb.png)
Hover volume :
![hover2](https://cloud.githubusercontent.com/assets/11486364/6655862/f1160ac6-cb11-11e4-9cca-0cae4c3a40e8.png)

**Comment by pixelr0** [comment]
+1 video with the bug on Ubuntu 15.04 https://www.youtube.com/watch?v=z0VvhQhsEvE&t=100
