### ISSUE TITLE
What is the proper way to install this theme?

### ISSUE THREAD

**Issue by nahtnam** [snwh/paper-gtk-theme#113]
Hey!

I am running Ubuntu 14.04.

I was wondering what the proper way to install this theme is. I am pretty new to theming so I have no idea. I am running whatever default theme software that ubuntu provides (not sure if its gnome, unity, etc.) I installed this theme VIA Unity Tweak Tool, and its working OK but It doesnt look like the images provided here: http://snwh.org/paper/gnome-shell-theme/

EDIT: I am using the daily ppa builds

**Comment by snwh** [comment]
First, the screenshots are for GNOME Shell. Also, I'm pretty certain the version of GNOME included in 14.04 is modern enough to get the same results –Paper theme relies on some newer aspects of GNOME/GTK, such as client-side decorations and GtkHeaderBars

**Comment by nahtnam** [comment]
@snwh But if I install the theme and fonts, and open up the search bar (windows key), it still looks like this: http://i.imgur.com/vb0zl60.png instead of this: http://snwh.org/paper/gnome-shell-theme/

**Comment by snwh** [comment]
Umm, that's because you are using Unity and not GNOME Shell.

**Comment by nahtnam** [comment]
@snwh Right. How can I switch to gnome. (Sorry, total noob here).

Thanks.

**Comment by snwh** [comment]
There are many people/sites that have written guide for setting up GNOME (such as this one for instance: http://www.webupd8.org/2014/05/how-to-install-gnome-312-in-ubuntu.html) but it should be as simple as installing gnome-shell, which you can do in a terminal with:

    sudo apt-get install gnome-shell

**Comment by nahtnam** [comment]
Got it! Thanks.
