### ISSUE TITLE
Weird Chrome Forward and Back Icons.

### ISSUE THREAD

**Issue by nahtnam** [snwh/paper-gtk-theme#114]
Im not sure if its intended, but in chrome the forward and back icons change to something that looks kind of like a trash can. http://i.imgur.com/6WxgJfT.png

Was that intended or is it a bug?

**Comment by snwh** [comment]
Related to: https://github.com/snwh/paper-icon-theme/issues/13

**Comment by nahtnam** [comment]
@snwh Thanks. I searched for chrome and couldnt find anything here. Forgot there was a second github repo.
