### ISSUE TITLE
How do you uninstall?

### ISSUE THREAD

**Issue by nahtnam** [snwh/paper-gtk-theme#115]
Hey!

I installed this theme through the install.sh file, and then realized that I want the package manager to handle it, so I removed `~/.local/share/themes/paper`, and `~/.local/share/icons/paper`, and installed it throught the package manager. Now its showing showing duplicate theme options, so it looks like I missed a file/folder while uninstalling the previous installation.

Any help would be appreciated.

**Comment by snwh** [comment]
There's also a folder in ```~/.themes``` and possibly ```~/.icons```.

**Comment by nahtnam** [comment]
Thanks a lot! I really appreciate it!

**Comment by panchal386** [comment]
One is inside ```~/.local/share/themes/```
and the other is in ```/usr/share/themes```

**Comment by nahtnam** [comment]
Got it!
