### ISSUE TITLE
Last Clicked Items Keeps Clicked Color

### ISSUE THREAD

**Issue by rockon999** [snwh/paper-gtk-theme#118]
When you click a widget (i.e. combobox, arrows in the dash's calendar) they stay highlighted like you are clicking them even after the click is done. I know screenshots speak louder than words, but every time I try to screenshot the problem it takes the focus away from the widget and therefore returns it to normal color.

**Comment by snwh** [comment]
For GNOME Shell?

**Comment by rockon999** [comment]
For Gtk and Gnome Shell. When I use a combo box it turns grey when I click on it, and stays grey even after I close the combo box's menu. It doesn't turn white again until it loses focus. Is this intentional? Here I took some pictures with my phone (I darkened my top bar to #2D2D2D as an experiment)...

![img_20150321_214830_670](https://cloud.githubusercontent.com/assets/2943271/6767780/3a2dcbf2-d014-11e4-8151-f94ffdcc980e.jpg)
![img_20150321_214821_912](https://cloud.githubusercontent.com/assets/2943271/6767781/3a2f4a18-d014-11e4-9653-9fd22f3c46cb.jpg)
![img_20150321_214815_234](https://cloud.githubusercontent.com/assets/2943271/6767782/3a3d3aa6-d014-11e4-98df-7f1c87292612.jpg)
![img_20150321_214808_555](https://cloud.githubusercontent.com/assets/2943271/6767783/3a4264b8-d014-11e4-8638-67c8b8173fd1.jpg)
![img_20150321_214802_581](https://cloud.githubusercontent.com/assets/2943271/6767784/3a425b3a-d014-11e4-982e-34e02853e781.jpg)
![img_20150321_214754_645](https://cloud.githubusercontent.com/assets/2943271/6767786/3a478f06-d014-11e4-939b-af3de3034ecb.jpg)
![img_20150321_214732_873](https://cloud.githubusercontent.com/assets/2943271/6767787/3a47ae8c-d014-11e4-888f-005d65c517d9.jpg)
![img_20150321_214728_360](https://cloud.githubusercontent.com/assets/2943271/6767785/3a46abb8-d014-11e4-900b-3e461f2709ff.jpg)

**Comment by dktcoding** [comment]
@rockon999 I experience this issue a couple of weeks ago (In Fedora 21), it went away when away using the ```User Themes``` [extension](https://extensions.gnome.org/extension/19/user-themes/). 
Hope it helps

**Comment by snwh** [comment]
I think I fixed this.
