### ISSUE TITLE
titlebar is not centered

### ISSUE THREAD

**Issue by region51** [snwh/paper-gtk-theme#123]
@snwh. hi, titlebar is not centered.
#### Paper
![2015-03-31 18 53 18](https://cloud.githubusercontent.com/assets/10940138/6923047/1aab0dfa-d7d8-11e4-8760-e85d5aa45cb9.png)

#### In Adwaita normal
![2015-03-31 18 53 50](https://cloud.githubusercontent.com/assets/10940138/6923072/40e93ff0-d7d8-11e4-9cbd-f50646cc336e.png)

**Comment by snwh** [comment]
I can't confirm this; it is centred on my end.

**Comment by Twixx** [comment]
Hello !
I can confirm, title is centered on space without the size of buttons. If i have 1 button (close for exemple) or 3 (reduce, maximize and close), title is not centered in a same way.

**Comment by Twixx** [comment]
Problem solved with gnome 3.16...
