### ISSUE TITLE
Enhancement: translucent window borders

### ISSUE THREAD

**Issue by jayay** [snwh/paper-gtk-theme#124]
Wouldn't it be nice to make the window header bars translucent, as I did it here for nautilus?
This would apply for GTK3 only (I guess...).
![screenshot from 2015-04-01 21 35 51](https://cloud.githubusercontent.com/assets/2384578/6949925/9cced26e-d8b7-11e4-88f6-c805b1f316d6.png)

**Comment by snwh** [comment]
Since elements behind the headerbars are clearly visible it would make headerbar elements illegible or hard to see in far too many cases.

If I were able to blur as well has have transparency, I would do it slightly.

**Comment by jayay** [comment]
OK. Even though it's a very weak argument, it's your decision.

**Comment by snwh** [comment]
You're right, the argument for transparency is weak.

**Comment by senfi** [comment]
+1 on translucent bars. The theme is really great, but this would give it some kind of more futuristic look. It would help to set it apart from some more old-fashioned themes.

**Comment by snwh** [comment]
Not happening folks. Translucency is not available, transparency is and I don't want other elements to be visible through the headerbars.
