### ISSUE TITLE
I updated and the gnome music controller add-on looks wierd

### ISSUE THREAD

**Issue by kimamb** [snwh/paper-gtk-theme#125]
(The top part)

![screenshot from 2015-04-03 23 35 10](https://cloud.githubusercontent.com/assets/10121762/6989295/3437b672-da5a-11e4-828b-57ea0d6fed36.png)

**Comment by kimamb** [comment]
This looked normal before i updated paper

**Comment by snwh** [comment]
I think more worrying is your use of Internet Explorer

**Comment by kimamb** [comment]
School...

**Comment by snwh** [comment]
I can't be certain of what controls the style of those button.

**Comment by kimamb** [comment]
I don't know, it was kinda grey-ish before. The extension is called Media Player Indicator

**Comment by kimamb** [comment]
Also, the circle you see. It was a box before.

**Comment by snwh** [comment]
What version of GNOME shell is this?

**Comment by kimamb** [comment]
I don't know, how do i check?

**Comment by snwh** [comment]
Run ```gnome-shell --version``` in the terminal

**Comment by kimamb** [comment]
kim@kim-LAPTOP:~$ gnome-shell --version
GNOME Shell 3.12.2

**Comment by kimamb** [comment]
I just released that it has changed colour form dark grey to the same colour as the top bar.

**Comment by kimamb** [comment]
Look at the screenshot on the extensions page: https://extensions.gnome.org/extension/55/media-player-indicator/ . Thats how the buttons looked before

**Comment by kimamb** [comment]
I'm now running GNOME shell 3.14 and the problem is still there
