### ISSUE TITLE
Non-client side decorated apps have thick titlebars

### ISSUE THREAD

**Issue by jlacson** [snwh/paper-gtk-theme#127]
I don't know if this is intended, because a screenshot I saw didn't have this effect. 

![Screenshot -- notice thickness of Firefox titlebar and thickness of gnome-system-monitor](https://cloud.githubusercontent.com/assets/2222566/6996719/f4f56fce-db65-11e4-80e2-e4558c3a178b.png)

**Comment by snwh** [comment]
It is an intended effect.

**Comment by jlacson** [comment]
Is there an earlier commit with thin titlebars? How could I modify the theme to make them narrower?

**Comment by snwh** [comment]
You can't. In doing so you'd make everything thinner. The client-side decorations have all the same style.

**Comment by snwh** [comment]
But, I'll see what I can do.
