### ISSUE TITLE
Transparent tooltip-background on Fedora's firefox 37

### ISSUE THREAD

**Issue by HeikoAdams** [snwh/paper-gtk-theme#130]
At least on Fedora Firefox 37 supports transparent tooltips but this makes them ATM nearly unreadable because of white text on a transparent background.

**Comment by HeikoAdams** [comment]
Providing a screenshot won't help you because of the white-on-transparen-background you wouldn't see anything helpfull

**Comment by HeikoAdams** [comment]
Maybe this helps
![bildschirmfoto_2015-04-18_22-39-24](https://cloud.githubusercontent.com/assets/1418818/7217207/d32720fc-e61b-11e4-9e36-84ad4a08a90c.png)

**Comment by snwh** [comment]
This bug no longer seems to be present.
