### ISSUE TITLE
Bugs with GNOME 3.16

### ISSUE THREAD

**Issue by XIAZY** [snwh/paper-gtk-theme#132]
After enable paper as GTK theme, entering gnome-control-panel will cause some icons invisible until scroll up or scroll down.

**Comment by XIAZY** [comment]
Also, after insert a USB storage drive, the text in notification box appear will become white and unreadable.

**Comment by mdeboer** [comment]
Also some issues with the window buttons and menubar. As you can see the menubar on an in-active window looks great but the window buttons look like they were hovered (underlined). On an active window the menubar looks like crap with a shadow but the window buttons look fine but have no hover effect when hovering.

![screenshot from 2015-04-14 00-16-18](https://cloud.githubusercontent.com/assets/1171956/7126702/c18d3bf8-e23b-11e4-9999-2e4138c54fa9.png)
![screenshot from 2015-04-14 00-17-24](https://cloud.githubusercontent.com/assets/1171956/7126705/c64449f2-e23b-11e4-9eed-c677a5ccfb08.png)

**Comment by xxxifan** [comment]
@mdeboer same here.

**Comment by snwh** [comment]
This bug is no longer applicable to the current version of the Paper theme. Closing
