### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by mumuhajir** [snwh/paper-gtk-theme#134]
Look at the close icon ( x ). It looks like pressed.
![screenshot from 2015-04-10 22-17-12](https://cloud.githubusercontent.com/assets/11854557/7090829/e70cc8b2-dfcf-11e4-9781-364a3f2b32d3.png)

**Comment by snwh** [comment]
No, that's the :hover state.

**Comment by mumuhajir** [comment]
but i didn't put my cursor on close icon,
it's not only on terminal, but also in others programs like geany, rhythmbox .
but everything's fine on gnome app (nautilus, calculator, etc)

**Comment by snwh** [comment]
Hmm, it may be a bug then.

**Comment by SCSmithr** [comment]
That may be a bug with the 3.16 gnome shell update since I had the same thing happen with the default Adwaita theme. This only happens with gnome terminal for me.

**Comment by mumuhajir** [comment]
Right..
It fixed after i update to gnome 3.16.1
