### ISSUE TITLE
Openbox

### ISSUE THREAD

**Issue by blasterbug** [snwh/paper-gtk-theme#136]
Will you make a theme for Openbox ? Could be quiet amazing ! ;)

**Comment by snwh** [comment]
It could. But I'm not that motivated to do so currently.

**Comment by JackieMium** [comment]
strongly recommend Openbox Paper theme!
Awaiting...

**Comment by snwh** [comment]
I'm going to say no. But if someone wants to submit one, I'm not opposed.

**Comment by blasterbug** [comment]
I will make as soon as i can ;)


Le jeu. 17 mars 2016 à 2:26, Sam Hewitt <notifications@github.com> a 
écrit :

**Comment by PwnArt1st** [comment]
@blasterbug any progress?

**Comment by blasterbug** [comment]
I just forget about this.  I got pretty busy. I can promise doing it soon, but if someone else wants to help, he is more than welcomed.

**Comment by Narrat** [comment]
Someone made a beginning as it seems
https://www.box-look.org/p/1017424/

Dunno how it looks in real

**Comment by PwnArt1st** [comment]
i am currently using tissuebox, it looks alright but i think an official one could be better

**Comment by JackieMium** [comment]
@Narrat @PwnArt1st 
I think TissueBox is great. Thanks for letting me know. Here is a screenshot of mine:
![2016-07-02-172025_1366x768_scrot](https://cloud.githubusercontent.com/assets/12944832/16539568/d4c14c44-4079-11e6-91da-016b5ec0ee84.png)

**Comment by Narrat** [comment]
Only quirks I noticed so far, is the missing hover icon for max_toggled icon and the desktop switch OSD.
Although the latter is fixed by adding this to the themerc

```
osd.hilight.bg: flat solid
osd.hilight.bg.color: #d9dcde
osd.unhilight.bg: flat solid
osd.unhilight.bg.color: #888888
```
Still need some better color for unhilight.
And hilight color needs to be adjusted if not using the wolf version. The value of menu.items.active.bg.color should be used in that case
