### ISSUE TITLE
bug and/or request: Chrome GTK+ portion Looks good and bad (mostly good)

### ISSUE THREAD

**Issue by kimamb** [snwh/paper-gtk-theme#137]
A picture says a million words; two says 2 million words.
Here:

![screenshot from 2015-04-11 22 50 37](https://cloud.githubusercontent.com/assets/10121762/7103222/95837c56-e09d-11e4-811c-87769cd67c6b.png)

Settings:
 
![screenshot from 2015-04-11 22 52 56](https://cloud.githubusercontent.com/assets/10121762/7103223/969d05e4-e09d-11e4-9a1b-69df363a0194.png)

**Comment by snwh** [comment]
What's the problem here?

**Comment by kimamb** [comment]
![screenshot from 2015-04-11 22 57 51](https://cloud.githubusercontent.com/assets/10121762/7103244/32fc4364-e09e-11e4-989d-36da86b69042.png)

Those look ugly like **** but the rest looks normal, this usually does'nt happen in other themes.

**Comment by kimamb** [comment]
This is normal:

![screenshot from 2015-04-11 23 00 52](https://cloud.githubusercontent.com/assets/10121762/7103257/a297b5e6-e09e-11e4-8fbe-c3e29ce97927.png)

**Comment by snwh** [comment]
Those are the oxygen icons. That has to do with whatever your icon theme is.

**Comment by kimamb** [comment]
i'm using paper icons, i'l gladly move over there if wanted

**Comment by bil-elmoussaoui** [comment]
@kimamb This is not a Paper or any other theme issue. When you active "use system title bars and borders" the icons will be taken from the one used by default in your system (the icon theme). 
Maybe, Paper icons is not supporting theme yet, try using an other icon theme to check this out, or report them to Paper icons.

**Comment by snwh** [comment]
The Paper icons should have those icons included and they don't default to oxygen, which is odd.

**Comment by kimamb** [comment]
@bil-elmoussaoui
I know, I am using system borders because i like having them.

**Comment by kimamb** [comment]
Just want to show this:
![screenshot from 2015-04-11 23 06 20](https://cloud.githubusercontent.com/assets/10121762/7103268/a75a7d60-e09f-11e4-83e3-95482a135f47.png)

To confirm ;)

**Comment by snwh** [comment]
Strange.

**Comment by kimamb** [comment]
Have to say, you did a good job blending if you turn on system borders:

![screenshot from 2015-04-11 22 50 37](https://cloud.githubusercontent.com/assets/10121762/7103275/fd50d2f0-e09f-11e4-9f4b-3f4c3cbf26e5.png)

![screenshot from 2015-04-11 23 11 06](https://cloud.githubusercontent.com/assets/10121762/7103282/112c9dfe-e0a0-11e4-9d39-551a9a226f89.png)

V.S.

![screenshot from 2015-04-11 23 00 52](https://cloud.githubusercontent.com/assets/10121762/7103284/1f325646-e0a0-11e4-94af-605278d6362c.png)

![screenshot from 2015-04-11 23 12 03](https://cloud.githubusercontent.com/assets/10121762/7103287/2ec07020-e0a0-11e4-80ee-f3951ecd4cd9.png)

**Comment by kimamb** [comment]
Maybe this is to use for you: https://code.google.com/p/chromium/wiki/LinuxGtkThemeIntegration

**Comment by kimamb** [comment]
Quote: "The GTK+ port of Chromium has a mode where we try to match the user's GTK theme (which can be enabled under Wrench -> Options -> Personal Stuff -> Set to GTK+ theme). **The heuristics often don't pick good colors due to a lack of information in the GTK themes.** "

**Comment by snwh** [comment]
I've already integrated chrome into the GTK theme. -_-

**Comment by kimamb** [comment]
Soooooo... what is the problem then?

**Comment by kimamb** [comment]
Thing this helps; https://code.google.com/p/chromium/issues/detail?id=351693

It's about the oxygen theme?

**Comment by snwh** [comment]
An isolated case unrelated to the theme.

**Comment by snwh** [comment]
If you've fiddled around with KDE and such it will override GTK with chrome. This issue will not be present on a clean GNOME(-based) desktop install.

**Comment by kimamb** [comment]
oh ok, really sorry then.

P.S. You'r theme is amazing

**Comment by kimamb** [comment]
**sudo apt-get remove gtk2-engines-oxygen gtk3-engines-oxygen**

Fixed it.

**Comment by snwh** [comment]
:+1:

**Comment by kimamb** [comment]
kinda, but a restart might help / i can live with it.

![screenshot from 2015-04-11 23 44 07](https://cloud.githubusercontent.com/assets/10121762/7103381/bc2dcf58-e0a4-11e4-8433-277412e4cd10.png)

Thank you for you'r support and your thumb. now you can close this and marked it as "somthing"

**Comment by snwh** [comment]
The wonky icons are a simple fix I haven't gotten to yet.

**Comment by kimamb** [comment]
OK. if i had money (under 18 so can't use card online) I'd pay you. thanks.

here's some virtual "money" 💴 💶 💷 💵. 😁
