### ISSUE TITLE
Does paper-gtk-theme depend on gnome-themes-standard?

### ISSUE THREAD

**Issue by acgtyrant** [snwh/paper-gtk-theme#138]
If not, I will be glad to remove this unuseful dependence.

**Comment by snwh** [comment]
No. It's why gnome-theme-standard is not in the dependencies.

**Comment by acgtyrant** [comment]
OK, thank you!

**Comment by snwh** [comment]
Why do you ask?

**Comment by acgtyrant** [comment]
Because a packager add this "dependency" for [paper-gtk-theme-git](https://aur.archlinux.org/packages/paper-gtk-theme-git) in AUR.

**Comment by snwh** [comment]
It doesn't hurt to have the dependency, generally, if you've got a gnome desktop it's already installed.
