### ISSUE TITLE
Dark theme too bright

### ISSUE THREAD

**Issue by Chais** [snwh/paper-gtk-theme#139]
The background on the dark theme is quite bright. Too bright to properly read the white text, especially if the element is highlighted.
![bildschirmfoto von 2015-04-14 10-38-30](https://cloud.githubusercontent.com/assets/1783098/7133319/7261d9d8-e292-11e4-8e4b-cdbeaaede8cb.png)
As you can see, the highlighted element in tweak-tool is hardly readable. Similarly some of the colours on the terminal are barely visible. I tried different colour schemes (this is solarized right now) but it doesn't really make a difference.

**Comment by Nnidyu** [comment]
It's especially bad in Evolution (see attached screenshot fragment).

Some time ago the dark theme had better matching colors - I have updated Paper yesterday.

![screenshot from 2015-04-14 16 32 52](https://cloud.githubusercontent.com/assets/293573/7138983/f90f54e8-e2c3-11e4-84e9-2be89d890d15.png)

**Comment by stefanwuthrich** [comment]
agree with Nnidyu

**Comment by Chais** [comment]
I have to reopen this. This is not what I'd consider fixed. The basic themes should work with any suited color palette. This here is the "dark" theme with solarized colors.
![bildschirmfoto von 2015-04-27 11-35-33](https://cloud.githubusercontent.com/assets/1783098/7345040/9768a4b6-ecd1-11e4-8ced-c9273dd56632.png)
