### ISSUE TITLE
gedit sidebar separator problem

### ISSUE THREAD

**Issue by nlaplante** [snwh/paper-gtk-theme#140]
There's an awkward separator between the sidebar and the rest of the window in the headerbar. See screenshot.

![paper-bug-gedit-headerbar](https://cloud.githubusercontent.com/assets/141054/7137001/fee31b56-e283-11e4-9cff-752dc70fd75d.png)

Also the text "File browser" seems to be misaligned. This is on HiDPI.

**Comment by Salamandar** [comment]
-GtkPaned-handle-size: 0;

should be on line 22, file gtk-widgets.css.
Maybe the other instances of GtkPaned-handle-size (there are some others) should be replaced ?

**Comment by snwh** [comment]
Fixed
