### ISSUE TITLE
applications menu won't change style in Fedora 21

### ISSUE THREAD

**Issue by Antidote00** [snwh/paper-gtk-theme#141]
Hi Sam,

thanks for the great work! I'm using Fedora 21 (installed today) with Paper Theme and Icons. At first, i have the same problem as #19. Additionally the applications menu stays default and won't change. Also some icons within the application menu aren't displayed correctly. 

Here is a screenshot displaying the problems:
![screenshot from 2015-04-14 21 47 08](https://cloud.githubusercontent.com/assets/4086468/7145909/db76da56-e2ef-11e4-9ad8-6bd85569dd3d.png)

Best Regards,
Antidote

**Comment by bil-elmoussaoui** [comment]
For the the applications menus, you have to use a gnome extension for that "User Themes" You can install it from here using Firefox : https://extensions.gnome.org/extension/19/user-themes/ And then active it using gnome-tweak-tools. And you can then change the gnome-shell theme to Paper!

**Comment by bil-elmoussaoui** [comment]
Ps: you can change the gnome-shell theme using gnome-tweak-tools

**Comment by Antidote00** [comment]
Thanks for the fast answer bil-elmoussaoui. This worked partly. The only problem left, are the icons. I have tried to change between the themes and restarted a couple of times. No luck. Any ideas? 

![screenshot from 2015-04-15 23 34 54](https://cloud.githubusercontent.com/assets/4086468/7169687/128206fa-e3c8-11e4-9096-cb2086f41f97.png)

**Comment by bil-elmoussaoui** [comment]
If you are talking about the applications icons, i think the icon theme you are using dosent support all the icons. And from your sceenshot you seems to use paper icons. You can report the missing icons to Sam or try another icon theme.

**Comment by Antidote00** [comment]
Hi bil,

the icons are not missing. As you can see in the picture, there is a empathy icons in docky/plank. But within the applications menu it's missing. 

I have tried other icon themes, they work correctly.

**Comment by snwh** [comment]
This shouldn't be an issue anymore, what you were seeing were placeholders from early in the *icon* theme's development.
