### ISSUE TITLE
I meet `'none' is not a valid color name` error when I executed gitg

### ISSUE THREAD

**Issue by acgtyrant** [snwh/paper-gtk-theme#142]
(gitg:13793): Gtk-WARNING **: Theme parsing error: message-dialogs.css:106:26: 'none' is not a valid color name

	(gitg:13793): Gtk-WARNING **: Theme parsing error: message-dialogs.css:113:26: 'none' is not a valid color name

	(gitg:13793): Gtk-WARNING **: Theme parsing error: message-dialogs.css:120:26: 'none' is not a valid color name

	(gitg:13793): Gtk-WARNING **: Theme parsing error: calculator.css:42:26: 'none' is not a valid color name

	(gitg:13793): Gtk-WARNING **: Theme parsing error: calculator.css:52:26: 'none' is not a valid color name

	(gitg:13793): Gtk-WARNING **: Theme parsing error: calculator.css:64:26: 'none' is not a valid color name

	(gitg:13793): Gtk-WARNING **: Theme parsing error: calculator.css:75:26: 'none' is not a valid color name

	(gitg:13793): Gtk-WARNING **: Theme parsing error: calculator.css:91:26: 'none' is not a valid color name

	(gitg:13793): Gtk-WARNING **: Theme parsing error: calculator.css:102:26: 'none' is not a valid color name

	(gitg:13793): GLib-GObject-WARNING **: The property GtkCellRendererPixbuf:follow-state is deprecated and shouldn't be used anymore. It will be removed in a future version.

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: message-dialogs.css:106:26: 'none' is not a valid color name

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: message-dialogs.css:113:26: 'none' is not a valid color name

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: message-dialogs.css:120:26: 'none' is not a valid color name

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: calculator.css:42:26: 'none' is not a valid color name

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: calculator.css:52:26: 'none' is not a valid color name

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: calculator.css:64:26: 'none' is not a valid color name

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: calculator.css:75:26: 'none' is not a valid color name

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: calculator.css:91:26: 'none' is not a valid color name

	(WebKitWebProcess:13804): Gtk-WARNING **: Theme parsing error: calculator.css:102:26: 'none' is not a valid color name

If you do not think this bug belong to paper-gtk-theme, I will report it to GNOME.

I use paper-gtk-theme-git in Arch Linux.

**Comment by snwh** [comment]
This is already fixed, you may need to update.
