### ISSUE TITLE
some part of notification message is missing

### ISSUE THREAD

**Issue by ffxmi** [snwh/paper-gtk-theme#143]
It seems notification message's description has a line over it from the bottom displaying it without perfection. I have attached a screenshot of notification pop up placed on top using osd extension. 
![screenshot from 2015-04-15 12 51 41](https://cloud.githubusercontent.com/assets/5526765/7154052/8ec7bd4e-e36f-11e4-9c3c-c1186d121104.png)

Gnome 3.14.1 on Debian Jessie.

**Comment by snwh** [comment]
I cannot confirm that this issue is not related to the use of the extension. Notifications for vanilla GNOME 3.14 do not have this issue –as far as I'm aware.

**Comment by ffxmi** [comment]
Strange. It happened regardless of the extension. Other than font size settings nothing else was modified.

**Comment by ffxmi** [comment]
@snwh nailed it down to this new font i was using. Some part of it was not right.
Paper works well with rest of the fonts like cantarell and droid sans. Thanks for looking anyway.
