### ISSUE TITLE
Tiling not working for GTK (?) Apps

### ISSUE THREAD

**Issue by sencer** [snwh/paper-gtk-theme#144]
Nothing happens when I try to tile apps like Geary, California, Evince using Super-<Left>/<Right>, but I can tile Chromium, VIM, gnome-terminal etc.

**Comment by snwh** [comment]
Tiling has nothing to do with the GTK theme.

**Comment by sencer** [comment]
But it works when I keep everything same, and revert only the theme to default. I believe it has something to do with the min width allowed for a window, which might change with the width of decorations.

**Comment by snwh** [comment]
Hmm
