### ISSUE TITLE
Faded elements on elementary OS Freya

### ISSUE THREAD

**Issue by varlesh** [snwh/paper-gtk-theme#146]
Faded wingpanel (icons and text) and slingshot-launcher on elementary OS Freya.
![2015-04-17 11 45 11](https://cloud.githubusercontent.com/assets/8083855/7198715/8a9b3316-e4f7-11e4-8f63-fc1effc61768.png)

**Comment by hiden33** [comment]
Same bug here!

**Comment by snwh** [comment]
Same as #94
