### ISSUE TITLE
Please consider using release tags in your projects

### ISSUE THREAD

**Issue by 183amir** [snwh/paper-gtk-theme#148]
It would be much more convenient if you could use release tags.
Right now I am using `paper-gtk-theme-git` package from Arch Linux and I have to regularly and manually check for updates. But, Paper could be packaged in a way that it would update automatically with new releases if it had release tags in Github.

**Comment by snwh** [comment]
I could. But Paper hasn't reached a full non-beta release yet.

**Comment by snwh** [comment]
Everyone are early adopters and I can't control or tell people not to use it (or build AUR packages), just warn them that it may be buggy.

**Comment by 183amir** [comment]
You have some versioning scheme  which you use to push your releases in your PPA. Could you use those version numbers here too? You can always indicate that these are alpha or beta releases.
Also, I want to see release tags in Moka project too.

**Comment by snwh** [comment]
The PPA simply takes the commit number and uses it for a build.
