### ISSUE TITLE
Nautilus issue on Ubuntu 15.04

### ISSUE THREAD

**Issue by marcogiannini** [snwh/paper-gtk-theme#149]
There is a white line

![schermata del 2015-04-20 14 11 56](https://cloud.githubusercontent.com/assets/4943897/7229765/a1ef41d4-e767-11e4-9d4d-7be1dc2f58d1.png)

**Comment by mdeboer** [comment]
It seems to be a general Gnome 3.16 issue as many themes face that problem, even the default Adwaita theme has a thin line above the menubar that looks incredibly ugly.

**Comment by snwh** [comment]
It's a Unity problem. Stylistically, Paper's header bars have a highlight and since the Unity window manager simply "ignores" the header bars you will have inconsistencies like this in some themes.

**Comment by snwh** [comment]
Vanilla GNOME doesn't have this issue.
