### ISSUE TITLE
Missing Overlay Background

### ISSUE THREAD

**Issue by mthxx** [snwh/paper-gtk-theme#15]
In Gnome Videos (Totem), the control overlay while watching a video has no background, making the floating widgets look out of place.

Paper:
![screenshot from 2014-12-15 08 34 56](https://cloud.githubusercontent.com/assets/2966341/5437372/7c044ee6-8435-11e4-9787-503f6329b68a.png)

Adwaita:
![screenshot from 2014-12-15 08 35 14](https://cloud.githubusercontent.com/assets/2966341/5437376/81f9b318-8435-11e4-9655-4e6ed440403e.png)

**Comment by Psykopear** [comment]
I confirm the problem, on my archlinux the buttons change dimensions too when mouse hovering them
