### ISSUE TITLE
Recommendations to improve integration with Unity

### ISSUE THREAD

**Issue by marcogiannini** [snwh/paper-gtk-theme#150]
The integration with Unity is not complete. It would be nice to have the background of the applications in the launcher as Ambiance or Azure

![temi comparativa](https://cloud.githubusercontent.com/assets/4943897/7230074/c6e1f2cc-e76a-11e4-9c20-3d63604a4ff4.png)

**Comment by snwh** [comment]
I'm not going to add these –I think they're ugly.
