### ISSUE TITLE
Paper mouse? question

### ISSUE THREAD

**Issue by humbleRumble** [snwh/paper-gtk-theme#153]
Any plans for making an X11 Mouse Theme? If not thats fine too but i think it would look pretty darn cool.

**Comment by snwh** [comment]
If the mood strikes me.

**Comment by nlaplante** [comment]
:+1:

**Comment by humbleRumble** [comment]
coo coo

**Comment by snwh** [comment]
The mood struck me some time ago. It's now available. :)
