### ISSUE TITLE
Volume icon gets replaced by Paper

### ISSUE THREAD

**Issue by tdtmusic** [snwh/paper-gtk-theme#157]
I'm on elementary OS Freya and I applied the Paper theme. As you can see in the screenshot, the Volume icon gets replaced with an ugly icon, different from the others. This happens no matter what icon theme I choose, as long as Paper is the GTK theme, the volume icon is this.

![screenshot from 2015-05-03 01 25 02](https://cloud.githubusercontent.com/assets/12214667/7443074/3cc822f8-f13a-11e4-813d-a0b72ae40451.png)

**Comment by snwh** [comment]
That is peculiar and is not controlled by Paper. I can't choose the icons that appear in the panel.

**Comment by tdtmusic** [comment]
I would normally agree with you, but this happens only when applying your theme. The other icons on that panel are from the Faba-mono icon theme, and no matter what icon theme I choose, that volume icon stays the same while your theme is on.

**Comment by snwh** [comment]
Does this occur with different GTK themes?

**Comment by Defman21** [comment]
@snwh some icons in wingpanel uses the color for wingpanel object. (`WingpanelWidgetsPanel.menubar.background.panel`)

**Comment by tdtmusic** [comment]
Not at all, that's why it's so weird. Other themes decorate the windows & everything but leave the icons on the dock and the panel alone. Here's how it should look:

![screenshot from 2015-05-03 19 42 55](https://cloud.githubusercontent.com/assets/12214667/7445847/b5ee2f14-f1cc-11e4-91e4-3a9704e4ae72.png)

**Comment by snwh** [comment]
@Defman21 yes, I know. But that doesn't change the icon itself.

**Comment by tdtmusic** [comment]
Here's the default elementary theme on everything and Paper as GTK theme. The volume icon is still different from the others, but at least it's the same color:

![screenshot from 2015-05-03 20 35 11](https://cloud.githubusercontent.com/assets/12214667/7446053/0b03ea28-f1d4-11e4-9d28-d7df9258ce18.png)

**Comment by snwh** [comment]
It seems now, that it is therefore an icon theme issue so it's likely a problem with the Faba mono icons.

**Comment by tdtmusic** [comment]
What?! I just said that no matter what icon theme I choose, the volume icon is different than the others, how did you come to the conclusion that this is a Faba mono issue?!

**Comment by snwh** [comment]
Because the volume icon is okay using the elementary icon theme with Paper. The good news for you, is that I maintain Faba too. ;)

**Comment by tdtmusic** [comment]
It's not ok, as you can see in the shot it's LARGER than the other icons. :)

**Comment by snwh** [comment]
Because I know that wingpanel prefers 24px icons and seeing as the icon you're getting is the GNOME default icon (which is 16px) it is stretching which likely means that Faba-Mono is missing the necessary icon so the gnome fallback is appearing.

**Comment by tdtmusic** [comment]
Ok, but if Faba-mono is missing that icon, how come it looks good with any other GTK theme? 
P.S. If I apply Paper AND the Paper icon theme, everything is ok, all the icons are the same: 
![screenshot from 2015-05-03 22 07 34](https://cloud.githubusercontent.com/assets/12214667/7446433/d2a74eec-f1e0-11e4-9172-8c1779b02b6d.png)

**Comment by snwh** [comment]
That's cause the Paper icon theme has the necessary icon(s).

**Comment by tdtmusic** [comment]
I see. Well, I prefer the Faba-mono icons, they look very good in my opinion, both in the panel and in the dock (I like the icons to be "similar", if you know what I mean. These icons are in a square, Numix has them in circles, etc.), so I will wait for a fix. Thank you! :)

**Comment by snwh** [comment]
@tdtmusic i've pushed a possible fix and started a build for Faba-Mono.

**Comment by tdtmusic** [comment]
You sure did. Here's how it looks now:
![screenshot from 2015-05-03 23 36 30](https://cloud.githubusercontent.com/assets/12214667/7446815/43ccec6a-f1ed-11e4-93bf-c0e4c54db8c9.png)

It's not white like the others, but at least it's the same size :)
