### ISSUE TITLE
windows control incon under Ubuntu 15.04 not displayed correctly

### ISSUE THREAD

**Issue by maxiclo** [snwh/paper-gtk-theme#158]
In UBUNTU 15.04 windows control icons are not displayed correctly. 
Furthermore all the windows are of same grey colour.

![wndctrl](https://cloud.githubusercontent.com/assets/8681722/7444353/c611dd8a-f17e-11e4-9dc3-d90331b04adb.png)

**Comment by snwh** [comment]
This is how it is under Unity. http://snwh.org/paper/screenshots/unity1.png
