### ISSUE TITLE
Text issues in Dark theme

### ISSUE THREAD

**Issue by tdtmusic** [snwh/paper-gtk-theme#159]
Since my icon issue was fixed, I have one more thing to do before I stick with Paper as my default theme in elementary OS. I prefer dark versions of my themes, so I enabled that in elementary tweaks. The problem is that Paper doesn't get along very well with this, as you can see in the screenshot. Is there any way I can tweak the colors to have a good result?
![screenshot from 2015-05-03 23 39 13](https://cloud.githubusercontent.com/assets/12214667/7446846/8cb70f72-f1ee-11e4-8989-6b83a2c4cef9.png)

P.S. The normal version of Paper also has some text issues, as in the mouse-over text is hard to read:
![screenshot from 2015-05-03 23 37 49](https://cloud.githubusercontent.com/assets/12214667/7446847/9bb8c66e-f1ee-11e4-9474-0e1220fdb5ff.png)

**Comment by snwh** [comment]
These are bugs I can fix.

**Comment by tdtmusic** [comment]
Oh, I see. I didn't know that, since there's a warning when switching to "dark mode" that some apps will look bad, etc. This is great news, thanks again! :)

**Comment by snwh** [comment]
That's a generic warning.

**Comment by sendz** [comment]
It's easy to fix, change value of foreground color on `gtk-3.0/gtk-dark.css` file to a lighter color, I changed to `#F2F2F2` by myself, it works fine for me.
`@define-color foreground #F2F2F2;/* Foreground color */`

**Comment by snwh** [comment]
That changes all text of the dark theme.

**Comment by tomasjakab** [comment]
Similar issue #219.

**Comment by snwh** [comment]
Menu text has been update.
