### ISSUE TITLE
Translucent terminal bg is not translucent

### ISSUE THREAD

**Issue by humbleRumble** [snwh/paper-gtk-theme#160]
In the terminal profile settings dialog there is an option for a translucent background, I always use this feature as I can never remember what I'm supposed to be typing by the time I switch to the terminal window. Using this theme there is no transparency.

GNOME Shell 3.14.4
Linux 3.19.4-200.fc21.x86_64

Also text inside dialogs seems to have very little contrast, it would seem as if they are disabled until you click and see they aren't

**Comment by humbleRumble** [comment]
Nevermind must have been fixed lately as this is now a non-issue

**Comment by snwh** [comment]
So.. no bug?
