### ISSUE TITLE
"Shell theme" showing error after updating from 3.14 to 3.16

### ISSUE THREAD

**Issue by clauseggers** [snwh/paper-gtk-theme#163]
After upgrading my Ubuntu GNOME from the stock 3.14 to 3.16, I can no longer access or change the "Shell theme" in Tweak Tool. I’ve tried to uninstall Paper, but the issue persists. This might very well be an issue with something other than Paper, but any suggestions are welcomes as how to fix it.

![screen shot 2015-05-10 at 22 16 23](https://cloud.githubusercontent.com/assets/868987/7556112/6524d7b6-f764-11e4-996a-0e4f46c74347.png)

**Comment by snwh** [comment]
GNOME disables the user theme extension when you update, you may have to re-enable it.

**Comment by clauseggers** [comment]
Bingo! Thank you very much for the super swift answer :)

**Comment by snwh** [comment]
No problem. I usually keep on top of them.

**Comment by clauseggers** [comment]
If you don’t mind I have an extra question. I’ve been trying to things working again as they looked under 3.14. I’ve been having trouble getting the Gnome Shell to use the "Input" typeface, and I believe it’s because 3.16 moved the setting previously in gnome-shell.css into a binary file. So I made a ~.themes folder with a gnome-shell.css theme in it, with an @import url pointing to the location of the Paper theme. This brought back the Input font, but as I remember it the top-bar used to be black(?) and the menus too, but they look like below after the upgrade to 3.16. Ideas?

![screen shot 2015-05-10 at 23 19 49](https://cloud.githubusercontent.com/assets/868987/7556321/5774c07e-f76c-11e4-88d5-2111cad1ec0d.png)
![screen shot 2015-05-10 at 23 15 14](https://cloud.githubusercontent.com/assets/868987/7556322/579c7cea-f76c-11e4-970f-485f8d3aa0ea.png)

**Comment by clauseggers** [comment]
Nevermind! I managed to solve it with the local gnome-shell.css by overriding the salient sections.
