### ISSUE TITLE
Bugs with Gnome Shell in Fedora 22

### ISSUE THREAD

**Issue by Love4Taylor** [snwh/paper-gtk-theme#165]
![2015-05-21 20-16-19](https://cloud.githubusercontent.com/assets/6081912/7749835/e20636ca-0002-11e5-9339-3a8382c4ff63.png)

and the terminal can‘t  be transparent

**Comment by snwh** [comment]
What's the issue?

**Comment by Love4Taylor** [comment]
Can't expand the option

**Comment by MichSt** [comment]
Everything works
![default](https://cloud.githubusercontent.com/assets/9870743/7901038/f2175a08-077d-11e5-8043-48326e1efad8.png)

**Comment by streambinder** [comment]
I can confirm terminal doesn't get transparency. While opening it's perfectly transparent, but after few milliseconds it totally loses it.
