### ISSUE TITLE
Theme parsing error: header-bar.css:162:26

### ISSUE THREAD

**Issue by clauseggers** [snwh/paper-gtk-theme#166]
I’m getting these errors a lot in my logs. I’m running Gnome 3.16.2 and OpenSUSE Tumbleweed (rolling release).
`Gtk-WARNING **: Theme parsing error: header-bar.css:162:26: 'none' is not a valid color name
Could not detect FTS supports, disabling Dashboard search
PLEASE USE ZEITGEIST 0.9.11 or above`

**Comment by snwh** [comment]
Usually if it's a "Gtk-WARNING" it's not serious and usually doesn't impact how the theme looks. The other warning is nothing to do with themes at all.

**Comment by clauseggers** [comment]
Okay, coolio.
