### ISSUE TITLE
Strange frame in Transmission

### ISSUE THREAD

**Issue by MichSt** [snwh/paper-gtk-theme#172]
If all of the downloaded files will not fit in the window, the frame appears
![transmission_022](https://cloud.githubusercontent.com/assets/9870743/7901048/975a9a3e-077e-11e5-9883-b329d46b31bc.png)

If all of the downloaded files are placed in the window, there is no frame
![transmission_023](https://cloud.githubusercontent.com/assets/9870743/7901050/b6064e92-077e-11e5-8501-4b3d68bb5961.png)

Fedora 22, Gnome 3.16.2

**Comment by MichSt** [comment]
Fedora 22, Gnome 3.16.2

**Comment by postblue** [comment]
It seems to be related to Transmission itself not well supporting GTK 3.16 and the scroll effect.

**Comment by bil-elmoussaoui** [comment]
Try using the transmission with gtk 3.14

**Comment by pedrofleck** [comment]
Not a bug of Paper, happens with Adwaita 3.16 too

**Comment by snwh** [comment]
It's the overflow indicator.

**Comment by snwh** [comment]
Fixed
