### ISSUE TITLE
Birdie Buttons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-gtk-theme#175]
I wanted to be sure that those buttons can't be themed in gtk theme? 
![screenshot from 2015-06-01 01 07 17](https://cloud.githubusercontent.com/assets/7660997/7904430/97f8cea8-07fa-11e5-99dd-99dbb24bd626.png)

**Comment by snwh** [comment]
Those are icons that are part of birdie and can't be changed by the GTK theme.
