### ISSUE TITLE
More Colours

### ISSUE THREAD

**Issue by Binero** [snwh/paper-gtk-theme#177]
This isn't much of an issue as a suggestion. 

I really like this theme, it adds a lot of flatness and colourfulness that other GTK themes don't tend to. Most applications I use don't have a colour though. They are the same grey. (Transmission, qTox, GNOME Terminal, Skype etc. )

As such, maybe it'd be nice to set the default colour to something other than grey?

**Comment by snwh** [comment]
Many apps I cannot control. These colourful apps in screenshots of Paper are those with Gtk Headerbars, which I can only colour if the App has a custom class on the headerbar. Those you list, I am certain I can't theme so they get the default colour.

**Comment by Binero** [comment]
I think we fell under a misunderstanding here. I was more asking to change the default colour than to do the impossible task of recolouring all applications individually. :)

**Comment by snwh** [comment]
No, I want the neutral-ish grey-blue so it's not a colour overload.
