### ISSUE TITLE
There are large file objects in this repo's .git history

### ISSUE THREAD

**Issue by lots0logs** [snwh/paper-gtk-theme#183]
I'm not sure if you noticed, but this repo is a 133.29 MiB download when cloned. There must be some large file objects in the history. This might be helpful to you: http://blog.jessitron.com/2013/08/finding-and-removing-large-files-in-git.html

Cheers!

**Comment by 0X1A** [comment]
@lots0logs I've contacted Sam before about this and he said he didn't think it was an issue, this is also the case with the Paper icon theme repository

**Comment by lots0logs** [comment]
While its not really an "issue" for me personally, it is certainly an issue for users who have limited bandwidth or low speed connections. I just wanted to make the developer aware of the issue. What they chooses to do is up to them :smile:

**Comment by snwh** [comment]
Fixed. ;)

**Comment by lots0logs** [comment]
:+1:

**Comment by snwh** [comment]
Considering it involved not a lot of effort. ;)
