### ISSUE TITLE
Inconsistent window style

### ISSUE THREAD

**Issue by peduxe** [snwh/paper-gtk-theme#190]
[Preview](http://i.imgur.com/egc1aGR.png)

I'm using Xubuntu 15.04 and the gnome shell is 3.16 but it still doesn't apply the window style to all windows, is there any way to fix this?

Also, the panel.

**Comment by yuryrodrigues** [comment]
DE: Gnome-Shell 3.16.2
OS: Antergos/Arch

The problem was found in the File-Roller(Archive Manager) application.

**Comment by snwh** [comment]
Yes, this happens because of conflicts with window managers and header bars. XFCE's window manager doesn't support headerbars and as a mostly GTK2 desktop (still) Paper doesn't appear at its best on it.

Nothing you can do to "fix" this if you stick with XFCE.

**Comment by Defman21** [comment]
@peduxe You can try to increase `title-[1-5]-[active|inactive].xpm` and `top-[left|right]-[active|inactive].xpm` heights in GIMP. Also you should change `button_spacing` and `button_offset` properties in this file: https://github.com/snwh/paper-gtk-theme/blob/master/Paper/xfwm4/themerc
But I'm not sure if this will work. It's a very dirty and hacky method and doing it may cause other problems. :confused:

**Comment by peduxe** [comment]
Yea, no way to set this close to the expected when once uses xfce.
