### ISSUE TITLE
problems with Rhythmbox and some ideas

### ISSUE THREAD

**Issue by alim0x** [snwh/paper-gtk-theme#191]
Gnome 3.14

Here is screenshot under default theme and paper:
![screenshot from 2015-06-30 22 05 08](https://cloud.githubusercontent.com/assets/4954007/8432689/200afc86-1f74-11e5-9167-dbdd56546f17.png)

Two button at the right of next button is in "on", but in paper theme:

![screenshot from 2015-06-30 22 07 07](https://cloud.githubusercontent.com/assets/4954007/8432734/62d276d4-1f74-11e5-8fe3-50f9941fa396.png)

I can't know the status of these button, maybe it's bug.

Other ideas:
![screenshot from 2015-06-30 22 10 57](https://cloud.githubusercontent.com/assets/4954007/8432837/fb4caa7e-1f74-11e5-9996-68c366dcfbb9.png)
I think it's maybe better to remove the border of hovered item, or transparent when hover, like defalt theme do.
And the progress bar when download things, like Software Updater and Software Center, I think it would be better to remove the border to make it looks better.

like this progress bar, color of done and other part color are same, looks strange.
![screenshot from 2015-06-30 23 44 40](https://cloud.githubusercontent.com/assets/4954007/8435240/ce353c82-1f82-11e5-9f36-a2cd09cea214.png)

Hope things above would be helpful :)

**Comment by snwh** [comment]
Rhythmbox itself adds padding to a default button style –which is why they're huge. If I could make them smaller I would.

**Comment by alim0x** [comment]
Sorry maybe I didn't make it clear
![p50701-114158](https://cloud.githubusercontent.com/assets/4954007/8447220/f8006702-1fe7-11e5-8ed4-8969fa703d61.jpg)
![p50701-114207](https://cloud.githubusercontent.com/assets/4954007/8447221/fb6a9624-1fe7-11e5-8554-969f4aafb421.jpg)
![p50701-114016](https://cloud.githubusercontent.com/assets/4954007/8447223/00aecccc-1fe8-11e5-9537-a562297fcd0a.jpg)

And another problem is, when a button is clicked, it stayed in "clicked" state, like this:
![p50701-114027](https://cloud.githubusercontent.com/assets/4954007/8447238/3045479a-1fe8-11e5-80d2-c639d3f7ced7.jpg)
![p50701-114051](https://cloud.githubusercontent.com/assets/4954007/8447239/32d8b65e-1fe8-11e5-8ae9-cfc370673949.jpg)

**Comment by snwh** [comment]
Hmm, the icons are supposed to grey out for clicked states.

**Comment by snwh** [comment]
Fixed.
