### ISSUE TITLE
Screensize of Geary 0.10

### ISSUE THREAD

**Issue by Steindi01** [snwh/paper-gtk-theme#192]
It is not possible to maximize the e-mail client Geary (version 0.10), when I use paper-theme. The maximize button is disabled and as a result either left or right side is always cropped.

![geary_001](https://cloud.githubusercontent.com/assets/803596/8435936/c053d57a-1f54-11e5-873f-31032829cb21.png)
![geary_002](https://cloud.githubusercontent.com/assets/803596/8435935/c05004a4-1f54-11e5-9efb-3fd02a4fe7b8.png)
If you compare paper-theme to default theme there is no "X" for closing the application, which is "outside" the displayed screen. Is it possible to reactivate maximization?

**Comment by snwh** [comment]
This is nothing to do with Paper. GNOME Tweak Tool has the option to enable/disable the minimize & maximize buttons.
