### ISSUE TITLE
Firefox 42 (Nightly): Highlight of Prev/Next/Reload/Bookmark entries in context menu awkwardly aligned

### ISSUE THREAD

**Issue by 2ion** [snwh/paper-gtk-theme#207]
Firefox 42 (now nightly) is using GTK3. The look of the browser with Paper has changed considerably.

The spacing between menu items in both the context menu and menu bar has widened. Looks good for the most part but the navigation buttons in the site context now have awkward highlighting:

![ff42context paper](https://cloud.githubusercontent.com/assets/666784/9088662/87f189b2-3b91-11e5-8d75-810bc9391797.png)

I feel that the button should cover its whole 'cell' / the topmost separator and its surrounding padding be somehow minimized/removed.

**Comment by snwh** [comment]
It's probably now using the default toolbar button style of Paper and as toolbars aren't generally in a menu there may be clashes like this.
