### ISSUE TITLE
Firefox 42 (Nightly): Tab bar background is now dark/grey

### ISSUE THREAD

**Issue by 2ion** [snwh/paper-gtk-theme#208]
This is a departure from the Paper look of the preceeding Firefoxes and breaks the consistency with other applications' style.

![2015-08-05-164921_1779x70_scrot](https://cloud.githubusercontent.com/assets/666784/9088762/0ba1c7a4-3b92-11e5-8959-51050067a0a4.png)

**Comment by 2ion** [comment]
Sorry.

I do not use other GTK3 applications, but the 'header' widget seems to be dark in other GTK3 programs.

**Comment by snwh** [comment]
Indeed it is. ;)
