### ISSUE TITLE
[invalid, nvm - sry] No window action buttons (min/max/close) on some apps

### ISSUE THREAD

**Issue by mcdope** [snwh/paper-gtk-theme#211]
On some apps, I assume those are GTK2, I get no buttons for window actions like minimize etc. 

The buttons are there and work, just not visible.

Shown on this screenshot are Trillian 2.0.0.5 and VirtualBox 5.0.2, also affected is Komodo IDE 9 and some other.

![bildschirmfoto vom 2015-08-18 13-13-04](https://cloud.githubusercontent.com/assets/3312979/9328706/4b362d42-45ab-11e5-9b66-4906b22323e3.png)

**Comment by Defman21** [comment]
But it's not Paper, it's Arc theme...

**Comment by mcdope** [comment]
lol wtf your right... nvm, total mess up on my side :D

**Comment by snwh** [comment]
Best bug filing ever.
