### ISSUE TITLE
Can't Choose Theme

### ISSUE THREAD

**Issue by SavoyRoad** [snwh/paper-gtk-theme#212]
I'm running Linux Mint 17.2, and I can't seem to select the theme for my desktop.

I've gone through every install method: first the daily PPA, then manually installing it in my home folder as per the instructions in the archive (PPA already installed in in /usr).  The PPA seemed to install everything fine; I was able to select Paper as the theme for my controls, icons, and window borders, but nothing shows up under desktop theme.  I even tried setting it through the terminal with this command:

`gsettings set org.gnome.desktop.interface gtk-theme "Paper"` 

and it doesn't seem to do anything; I'm stuck with the previous desktop theme.

**Comment by snwh** [comment]
There is no Paper Cinnamon (the desktop) theme.

**Comment by arcooke** [comment]
Is this the case with MATE as well?  I've seen other people mention using MATE but paper does not show up for me to select in Mint MATE

**Comment by snwh** [comment]
MATE would has it's own settings keys and setting it may be something like this ```gsettings set org.mate.desktop.interface gtk-theme "Paper"```

But MATE is also a GTK2 desktop, so Paper won't look all that good on it.

**Comment by snwh** [comment]
I don't know why it doesn't appear in the theme choosers.

**Comment by arcooke** [comment]
Thank you for the response, I'll keep poking around with it.  Great work on the theme, definitely one of the nicest I've seen so far.
