### ISSUE TITLE
Not working on gtk2 applications

### ISSUE THREAD

**Issue by LuisAlejandro** [snwh/paper-gtk-theme#215]
Hi, I'm using Debian Sid with Gnome 3.16.2, and the gtk2 theme doesn't work. Is there a way i can debug it? I used awf to try it, but it doesn't even appear on the menu. I attached some screenshots.

Thanks and let me know if i can be of further help to resolve this issue.

![captura de pantalla de 2015-08-30 12-26-19](https://cloud.githubusercontent.com/assets/324683/9568425/8599485a-4f12-11e5-8da8-ef28111f5669.png)
![captura de pantalla de 2015-08-30 12-26-49](https://cloud.githubusercontent.com/assets/324683/9568426/859dc2f4-4f12-11e5-8be6-7fe70c470cba.png)
![captura de pantalla de 2015-08-30 12-27-01](https://cloud.githubusercontent.com/assets/324683/9568427/85a6ae96-4f12-11e5-92ec-ca63c5d09892.png)

**Comment by snwh** [comment]
You'll need to install ```gtk2-pixbuf-engine``` or whatever the package name is.

**Comment by LuisAlejandro** [comment]
Its already installed, its not that.

**Comment by LuisAlejandro** [comment]
Oh, i installed it manually and apparently, it put it on ~.local/share/themes and not in ~.themes

Nevermind, thanks.
