### ISSUE TITLE
Header bug with California calendar

### ISSUE THREAD

**Issue by sbaconnais** [snwh/paper-gtk-theme#217]
The california calendar header doesn't merge on Ubuntu Gnome 15.04.

![capture du 2015-09-08 13 34 06](https://cloud.githubusercontent.com/assets/5074414/9733981/f8d43522-562f-11e5-9e4d-e5fde02149df.png)

**Comment by snwh** [comment]
If a window manager doesn't support client-side decorations, then some apps will look like this –the window bar won't be merged into the header. Nothing I can do about this.

**Comment by sbaconnais** [comment]
But Ubuntu Gnome 15.04 works great with all others apps. The only app that doesn't merge peoperly is California.

Is it normal ?

**Comment by snwh** [comment]
It could be a California bug, I do not know. If other apps fit then, probably.
