### ISSUE TITLE
Menu highlight bug on eog

### ISSUE THREAD

**Issue by sbaconnais** [snwh/paper-gtk-theme#219]
Font of highlight elements is too light on eye of gnome under Ubuntu Gnome 15.04

![capture du 2015-09-08 13 54 53](https://cloud.githubusercontent.com/assets/5074414/9734222/963700be-5631-11e5-8844-1d5f9adcfc4f.png)

**Comment by eclipxe13** [comment]
I thing this is because eog (and totem) is using the dark theme, you will see the same issue if you set Global Dark Theme in gnome tweak tool, maybe working with `Paper/gtk-3.0/gtk-dark.css` could solve this issue ?

**Comment by snwh** [comment]
Same as #159
