### ISSUE TITLE
Geary color scheme

### ISSUE THREAD

**Issue by bkstar** [snwh/paper-gtk-theme#220]
Greetings. I would like to express my gratitude and congratulations for the great works in
faba, moka, and paper gtk/icon themes.  

Below is what I see in Geary
![screenshot from 2015-09-09 01 23 04](https://cloud.githubusercontent.com/assets/5339775/9754822/47b4fc3c-5692-11e5-8d72-42e1807cfe85.png)
I am using elementary os freya 0.3.1.  I don't use any new builds of GTK other than those
come with elementary. Both my Metacity and GTK+ theme are paper theme.
The version of paper gtk theme I got is the one from the paper daily ppa.
Please let me know if it is due to problems on my side. 

If not, I was wondering if a new color scheme could be released in the near future, which potentially would fix:
 i)  The mail list color scheme: it is difficult to read which is which mail in the list
ii)  The headerbar color: maybe change it back to yellow.

**Comment by snwh** [comment]
It was yellow, perhaps an update to Geary has changed my ability to make it yellow.

**Comment by pawelad** [comment]
Same here

**Comment by bil-elmoussaoui** [comment]
Works fine on Geary 0.10

**Comment by sencer** [comment]
2.0 update made the geary header gray as in this issue on Ubuntu 15.10. Downgraded to 1.1+r194 and it's beautiful again.

**Comment by vibou** [comment]
I found a workaround: add this to your /usr/share/themes/Paper/gtk3.0/gtk.css after all other defines
@define-color text_color #333;
