### ISSUE TITLE
[gnome-calendar] [GTK 3.16.2] Grave display bugs

### ISSUE THREAD

**Issue by 2ion** [snwh/paper-gtk-theme#223]
This is the appearance of gnome-calendar 3.16.2 under Paper:

### Monthly view

* The calendar grid is missing and makes the data hard to read.
* Month and year labels are missing (white on white?).

![2015-09-23-145127_996x712_scrot](https://cloud.githubusercontent.com/assets/666784/10045425/dd6d45e2-6202-11e5-86d8-35605dac872d.png)

In contrast, Adwaita has a grid and shows the current month:

![2015-09-23-145033_996x713_scrot](https://cloud.githubusercontent.com/assets/666784/10045448/15e3c928-6203-11e5-956d-0526623331a3.png)

### Yearly view

* The view stays completely empty (white on white?).

![2015-09-23-145134_996x712_scrot](https://cloud.githubusercontent.com/assets/666784/10045444/06168936-6203-11e5-864c-573d360ca712.png)

In contrast, Adwaita displays the view properly:

![2015-09-23-145151_996x713_scrot](https://cloud.githubusercontent.com/assets/666784/10045467/36f1255c-6203-11e5-9eb9-ccbed5234fc8.png)

**Comment by mdeboer** [comment]
Same here, I wonder what happens after the update to 3.18 though. This bug makes the app unusable though, very disappointing.

**Comment by 2ion** [comment]
Just found this possible duplicate: https://github.com/snwh/paper-gtk-theme/issues/151.

**Comment by JorisM** [comment]
Same here on Gnome 3.18.0 (Fedora 23 beta)

**Comment by snwh** [comment]
Yeah there's some things that I can't seem to figure out how to theme in the GNOME Calendar app.

**Comment by chrisirwin** [comment]
Submitted a pull request to add a few aliases that seem to be referenced explicitly in the gnome-calendar utility (thanks to gtk-inspector, adwaita theme sources, and gnome-calendar sources).

Month view is now legible with grid lines:

![calendar_001](https://cloud.githubusercontent.com/assets/6145931/13838682/53655e38-ebec-11e5-920a-9089442f337f.png)

Year view is semi-legible. However, month labels are still white-on-white.
![calendar_002](https://cloud.githubusercontent.com/assets/6145931/13838687/573dd710-ebec-11e5-82f1-0e594a33e0ed.png)
