### ISSUE TITLE
Gnome 3.18 Nautilus Sidebar

### ISSUE THREAD

**Issue by JorisM** [snwh/paper-gtk-theme#225]
There is an issue with nautilus (the sidebar) on F23 beta with Gnome 3.18.0

![bug_paper](https://cloud.githubusercontent.com/assets/294174/10216496/cf48c96e-6829-11e5-8f27-44b721d51f1f.png)

**Comment by NForce** [comment]
I've got this fixed in my local repo, you can grab it there, as this project is dead now, I suppose

**Comment by snwh** [comment]
You suppose incorrectly.

**Comment by snwh** [comment]
@NForce it is true that I haven't made time to work on Paper.

**Comment by JorisM** [comment]
works! thanks very much

**Comment by fallomermo** [comment]
This is best theme gtk custom.
