### ISSUE TITLE
gnome-software: homepage glitch

### ISSUE THREAD

**Issue by Danysan1** [snwh/paper-gtk-theme#226]
The homepage of gnome-software is glitched, see screenshots:

Original home page:
![Original home page](https://cloud.githubusercontent.com/assets/8406735/10249830/a14a83d2-6927-11e5-8a13-7380d587a983.png)

Themed home page:
![Themed home page](https://cloud.githubusercontent.com/assets/8406735/10249847/bd135e72-6927-11e5-8f79-bb530c75aba4.png)

System: Fedora 22
gnome-software  3.16.5-1.fc22
gtk3  3.16.7-1.fc22

**Comment by HoboPrimate** [comment]
I can confirm for Fedora 23 as well.

**Comment by snwh** [comment]
I've made some adjustments in the latest commits, let me know if you still are experiencing issues.
