### ISSUE TITLE
GTK2 theme not loaded

### ISSUE THREAD

**Issue by 2mac** [snwh/paper-gtk-theme#235]
I'm using GNOME 3.18, and after installing and selecting this theme (with shell theme or without), all GTK2 applications use the Windows 9x-esque default theme. I see there is a GTK2 theme directory in the theme, but it doesn't seem to have any effect except that there is no longer a theme.

**Comment by 2mac** [comment]
Possible solution: have I not installed a particular GTK2 engine that is required?

**Comment by snwh** [comment]
Sorry for the extraordinairily late reply. Paper requires ```gtk2-engines-pixbuf``` this may be what you are missing
