### ISSUE TITLE
[Gnome 3.18]Nautilus looks weird + Shut Down dialogue is not Paper.

### ISSUE THREAD

**Issue by kimamb** [snwh/paper-gtk-theme#236]
![screenshot from 2015-10-29 18-56-49](https://cloud.githubusercontent.com/assets/10121762/10827393/f85590f2-7e6e-11e5-8ade-07d97b255655.png)

There are white line between every line of text.

I can sadly not screenshot the shutdown dialog.

**Comment by pschichtel** [comment]
I can confirm this, and I think it not only affects nautilus.

**Comment by pschichtel** [comment]
duplicates #228
