### ISSUE TITLE
Theme is installed both to ~/.themes and ~/.local/share/themes 

### ISSUE THREAD

**Issue by saschalalala** [snwh/paper-gtk-theme#237]
Is there any special reason for that behaviour? For me, it just leads to confusion and gnome-tweak-tool shows 2 paper installations.

**Comment by squizzi** [comment]
On Fedora 23 `~/.themes` is a symlink to `~/.local/share/themes`: 

~~~
$ ls -l ~/.themes
lrwxrwxrwx. 1 ksquizza ksquizza 34 Dec 12  2014 /home/ksquizza/.themes -> /home/ksquizza/.local/share/themes
~~~

I imagine this is the behavior you're seeing and it's probably not paper-gtk's fault.

**Comment by snwh** [comment]
For a local installation, this is required to have full GTK2 support.
