### ISSUE TITLE
Icon problems with topicon extension

### ISSUE THREAD

**Issue by saschalalala** [snwh/paper-gtk-theme#239]
Using this extension (https://extensions.gnome.org/extension/495/topicons/), I have an ugly icon cropping problem looking like this: https://i.imgur.com/ztoZHBg.png.

I solved the problem by adding .panel-button { min-width: 48px; } to Paper/gnome-shell/gnome-shell.css fixes it and didn't create any new issues yet.
 WIll create a pull request this evening.

**Comment by kimamb** [comment]
I use the extension as well.

I do not have this problem.

**Comment by fishears** [comment]
I also use this extension with Paper and have no such problem.
