### ISSUE TITLE
Top panel does not use system fonts

### ISSUE THREAD

**Issue by somepaulo** [snwh/paper-gtk-theme#243]
Hello and thank you for this amazing work!
Just wanted to point out an issue I ran into on Arch with Gnome 3.18 (although the environment seems to be irrelevant).
gnome-shell.css sets font-family to Source Sans Pro, Cantarell, Sans-Serif
Any changes to system fonts are not reflected in the top panel.
Had to manually edit the said .css file to get consistency.
I think this is something that could be easily fixed.

**Comment by snwh** [comment]
IIRC, most themes don't detect changes in the system font.
