### ISSUE TITLE
Theme parsing error with either gnome-terminal or gedit

### ISSUE THREAD

**Issue by nscornia** [snwh/paper-gtk-theme#245]
Ubuntu 14.04 LTS 64-bit
3.13.0-45-generic 

**This error was created when the following command was run:**

**gnome-terminal &**

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:612:25: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:617:25: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:622:25: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:627:34: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:817:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:821:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:826:12: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:832:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:836:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:841:12: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:847:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:851:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:856:12: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:862:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:866:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:871:12: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:877:16: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:881:16: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:886:21: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:892:16: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:896:16: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:901:21: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:913:22: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1109:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1113:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1118:12: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1124:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1128:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1133:12: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1139:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1143:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1148:12: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1154:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1158:7: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1163:12: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1169:16: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1173:16: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1178:21: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1184:16: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1188:16: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1193:21: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: app-notifications.css:51:60: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: buttons.css:77:18: 'outline-radius' is not a valid property name

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: check-radio.css:98:52: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: header-bar.css:153:20: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: header-bar.css:168:25: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: header-bar.css:229:20: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: spinner.css:32:42: No property named '-gtk-icon-transform'

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: titlebar.css:153:18: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: titlebar.css:169:23: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: titlebar.css:231:18: Missing name of pseudo-class

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: nautilus.css:123:16: 'outline-radius' is not a valid property name

(gnome-terminal:10809): Gtk-WARNING **: Theme parsing error: unity.css:199:28: No property named '-gtk-icon-transform'

**This error was created when the following command was run:**

**gedit &**

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:612:25: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:617:25: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:622:25: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:627:34: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:817:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:821:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:826:12: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:832:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:836:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:841:12: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:847:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:851:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:856:12: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:862:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:866:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:871:12: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:877:16: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:881:16: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:886:21: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:892:16: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:896:16: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:901:21: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:913:22: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1109:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1113:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1118:12: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1124:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1128:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1133:12: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1139:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1143:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1148:12: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1154:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1158:7: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1163:12: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1169:16: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1173:16: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1178:21: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1184:16: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1188:16: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:1193:21: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: app-notifications.css:51:60: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: buttons.css:77:18: 'outline-radius' is not a valid property name

(gedit:10866): Gtk-WARNING **: Theme parsing error: check-radio.css:98:52: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: header-bar.css:153:20: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: header-bar.css:168:25: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: header-bar.css:229:20: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: spinner.css:32:42: No property named '-gtk-icon-transform'

(gedit:10866): Gtk-WARNING **: Theme parsing error: titlebar.css:153:18: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: titlebar.css:169:23: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: titlebar.css:231:18: Missing name of pseudo-class

(gedit:10866): Gtk-WARNING **: Theme parsing error: nautilus.css:123:16: 'outline-radius' is not a valid property name

(gedit:10866): Gtk-WARNING **: Theme parsing error: unity.css:199:28: No property named '-gtk-icon-transform'

**Comment by snwh** [comment]
This are warnings for newer classes or elements that aren't supported by the version of GTK shipped in 14.04, it's nothing that will affect your experience of the theme.
