### ISSUE TITLE
[Gnome 3.18] Top bar is missing corners

### ISSUE THREAD

**Issue by kimamb** [snwh/paper-gtk-theme#246]
![screenshot from 2015-11-27 21-31-27](https://cloud.githubusercontent.com/assets/10121762/11447892/90cc7c24-954e-11e5-9daf-cba50e623818.png)
Paper Theme

![screenshot from 2015-11-27 21-32-07](https://cloud.githubusercontent.com/assets/10121762/11447898/9e3c83d6-954e-11e5-996f-0449f15d4175.png)
Default

As you can see, the paper theme is missing that "bump" or "slide" that hides the wallpaper / rounded windows.

(EDIT: My wallpaper is red.)

You seem to have this fixed in moka

![screenshot from 2015-11-27 21-32-21](https://cloud.githubusercontent.com/assets/10121762/11447923/e0633688-954e-11e5-80c6-5370939c8919.png)

**Comment by snwh** [comment]
The lack of rounded corners is by design in Paper.
