### ISSUE TITLE
Windows are rounded off.

### ISSUE THREAD

**Issue by kimamb** [snwh/paper-gtk-theme#251]
Windows are rounded off and don't look that material design-y 

Here's how it looks on Chrome/Chromium OS
![chrome-gallery-mosaic-view](https://cloud.githubusercontent.com/assets/10121762/11792404/41d6d5d2-a2a6-11e5-8f5b-55854bd5eec8.jpg)
(Image source: OMG Ubuntu)

**Comment by snwh** [comment]
I don't follow material design 100%; Paper has been oversold as a Material design theme, which isn't really.

**Comment by kimamb** [comment]
What about the corners when windows are maximised in gnome 3? It's really irritating to look at.

**Comment by snwh** [comment]
That would be a different bug
