### ISSUE TITLE
Skype icon

### ISSUE THREAD

**Issue by c0b41** [snwh/paper-gtk-theme#257]
![ekran goruntusu - 2015-12-30 12 38 51](https://cloud.githubusercontent.com/assets/2834954/12049643/54599872-aef2-11e5-981a-69589f6eeb9d.png)
![ekran goruntusu - 2015-12-30 12 38 57](https://cloud.githubusercontent.com/assets/2834954/12049645/5e02fb20-aef2-11e5-9ee6-2e0b54e1c4e3.png)

**Comment by snwh** [comment]
Sorry, Skype's icons are unthemeable (and this is not an issue related to the GTK theme).
