### ISSUE TITLE
Problem with the headerbar of pantheon-terminal

### ISSUE THREAD

**Issue by aleksandar-todorovic** [snwh/paper-gtk-theme#26]
There's a huge problem with the pantheon-terminal. First of all, if I have two applications opened and the terminal is in the background, the headerbar becomes _completely_ transparent.

![screenshot from 2014-12-18 16 21 54](https://cloud.githubusercontent.com/assets/4890548/5490490/24081e9e-86d2-11e4-8f51-ec1cd0ad1ac1.png)

If I put the focus back on the terminal, I get the same problem, but this time with the bar with tabs.

![screenshot from 2014-12-18 16 21 57](https://cloud.githubusercontent.com/assets/4890548/5490489/2401cb3e-86d2-11e4-8e2f-147a5f3ff53a.png)

Just cloned the theme from the git, so I'm guessing that I'm using the latest version of the theme. I'm using elementary OS Freya with the latest updates. I installed by copying the theme by copying the Paper folder to /usr/share/themes, haven't used the install.sh, maybe that has to do something with it?

**Comment by eboye** [comment]
I installed the theme via PPA on my Elementary stable setup and I'm having this issue on pantheon-terminal.

I guess PPA copied all the files, is there a specific fix for this? Where is the background color defiened?

![terminal problem](https://cloud.githubusercontent.com/assets/624357/6651650/caeb2554-ca4c-11e4-9af4-ec55c2cbe4d2.png)
