### ISSUE TITLE
Weird looking loading spinner in the top panel

### ISSUE THREAD

**Issue by DuckThom** [snwh/paper-gtk-theme#260]
The spinner that's showing when opening an application doesn't look quite right.

![http://i.imgur.com/H5YSEgy.gif](http://i.imgur.com/H5YSEgy.gif)

This is on a retina Macbook running Arch Linux with Gnome 3.18.3.

**Comment by addisonamiri** [comment]
I have the same problem on my Dell laptop running arch and the latest gnome.

**Comment by germanocorrea** [comment]
Same problem with arch linux and gnome 3.18 too

**Comment by TheKeyLimePie** [comment]
I have the same problem on my Dell XPS 13 (2015) (3200x1800px) running Fedora 23 with Gnome 3.18.3.

**Comment by remi6397** [comment]
Same problem is occuring for me on Arch Linux Gnome 3.18.2.

**Comment by DuckThom** [comment]
Changing the spinner to the default one, like in the issue @remi6397 mentioned, fixes the problem. 
I will create a pull request but I'm not sure if it's really a fix as it will just replace the current spinner with the default gnome-shell one. 
I think the only 2 options are to create a new svg spinner that has 60 animation steps or to just use the default spinner.

**Comment by germanocorrea** [comment]
The theme isn't updated since December, 2015...

**Comment by snwh** [comment]
@germanocorrea it's only been 3 months ;)

**Comment by germanocorrea** [comment]
Ok haha

I just thought you might be too much busy to pay attention at something in this theme right now, and somehow I think three months it's a long time :P

But I'm glad you're still tuned!

**Comment by snwh** [comment]
@germanocorrea I still get all the bug mail. ;)
