### ISSUE TITLE
[Question] How to change the gray window borders to another color

### ISSUE THREAD

**Issue by ajthemacboy** [snwh/paper-gtk-theme#261]
I think the gray window borders look a little bland by material design standards, and I'd like to know how to change them to something blue, or maybe red?

Is there a single CSS color code that I can change? Where is it? Would it be more complex?

**Comment by snwh** [comment]
Which borders are you referring to?

**Comment by ajthemacboy** [comment]
At the time I asked this I was using Ubuntu GNOME (I assume this applies to all vanilla GNOME environments) where the standard borders seemed to always be gray. 

Some applications like Calculator and System Monitor had colored borders if I remember correctly, and I wanted to know how to change the default gray to be blue or something.

I don't really need to know the answer to this anymore, but you might consider adding different styles, like a blue border theme and a red one, etc. or making it easy to change the color yourself.

**Comment by snwh** [comment]
I understand what you're asking now. The grey windows can't be simply changed to a colour and many apps' windows cannot be coloured at all. It's just how it is.

**Comment by lesderid** [comment]
I believe @ajthemacboy is referring to the actual window borders (drawn by the window decorator, e.g. gtk-window-decorator). Can't these be styled by a GTK theme?

**Comment by ajthemacboy** [comment]
@lesderid That is correct. I'm certain what I'm talking about can be changed; the Numix theme has a dark grey border, the Arc theme has white and black border variants, and Paper has a lighter gray border.

**Comment by snwh** [comment]
What desktop environment are you using Paper on?

**Comment by lesderid** [comment]
I have recently switched to i3, but I was using personally using MATE before (with marco). ([example screenshot](https://pomf.lesderid.net/f/oepalv.png))

**Comment by snwh** [comment]
Right, this is GTK2. So you would have to edit the main theme file [gtkrc](https://github.com/snwh/paper-gtk-theme/blob/master/Paper/gtk-2.0/gtkrc) changing the `(*_)wm_color`.
