### ISSUE TITLE
Installation under Unity is weird

### ISSUE THREAD

**Issue by MashedPotats** [snwh/paper-gtk-theme#269]
So far, I have downloaded the zip file from GitHub and ran `install.sh` under `sudo`. However, when I went into Unity Tweak Tool to change the theme, the theme only changes several aesthetics. The window including the Unity taskbar has not changed at all.

![image](https://cloud.githubusercontent.com/assets/9442368/13035089/de41c118-d2fb-11e5-995d-5642c07f46e4.png)

**Comment by MashedPotats** [comment]
Haha. I decided to install Ubuntu on the physical machine, and it works now. Must've been all of the stuff I broke on my VM.

**Comment by dragon788** [comment]
I installed via the PPA, and it took some Googling to figure out I had to use Unity-Tweak/Gnome-Tweak/Ubuntu-Tweak in order to apply the theme since Appearance didn't acknowledge it.
