### ISSUE TITLE
How to determine the name of the program window?

### ISSUE THREAD

**Issue by stagfoo** [snwh/paper-gtk-theme#271]
Hi all,
i want to help app new top bars but im not sure how you determine the top bar classes?
Is there a way to check the names on apps so i can start making more bars?

```
GeditPanel.horizontal .notebook {
    padding: 0;
    border-width: 0 1px 1px 0;
}
```

My other question is how is the naming convention for the files , is it process name?

**Comment by snwh** [comment]
There is no naming convention. The way I am doing this sort of theming is very hack-y and is dependent on whether or not an app uses a sane top-level application name like this –I find such top-level names using the GtkInspector.
