### ISSUE TITLE
Theme'd GIMP weird border discoloration.

### ISSUE THREAD

**Issue by DroWnThePoor** [snwh/paper-gtk-theme#274]
This is my GIMP installation with the Photoshop CS3 theme.I do not have this problem with other themes aside from Paper.
![bug2](https://cloud.githubusercontent.com/assets/16339020/13593479/7d73dc56-e4c9-11e5-99a1-8d59a6bcc480.png)

**Comment by snwh** [comment]
Paper's GTK2 theme uses image assets instead of drawing the borders, it will be incompatible with some custom GIMP themes. Like this one.
