### ISSUE TITLE
Paper is not found after last update in Ubuntu

### ISSUE THREAD

**Issue by Nosthertus** [snwh/paper-gtk-theme#277]
The last update made the theme to disappear from the list of themes.

Toolkit used for themes: Gnome-system-tools

**Comment by snwh** [comment]
Is the theme installed in ```/usr/share/themes/```?

**Comment by official-jkim** [comment]
Same issue, I'm using Gnome Tweak Tool.

**Comment by Nosthertus** [comment]
i can see the theme in `/usr/share/themes/` but still.. it cannot be found in the list of themes on the appearance config.. even if it is in Gnome Tweak Tool

**Comment by snwh** [comment]
Okay I'm going to push a new build to the PPA.

**Comment by snwh** [comment]
Build ```r192``` should have fixed this issue.

**Comment by Nosthertus** [comment]
should i reinstall it manually or there is a command that could take care of this update?

PS: 'im still learning how to use Linux/Ubuntu

**Comment by snwh** [comment]
When you next update your system, you should receive the update

**Comment by official-jkim** [comment]
Updated, but still it doesn't show up.

**Comment by official-jkim** [comment]
Thanks! now it's working.

**Comment by Nosthertus** [comment]
thanks. it works
