### ISSUE TITLE
GTK theme broken on elementary OS 0.3.2 Freya (64-bit)

### ISSUE THREAD

**Issue by mfkr5** [snwh/paper-gtk-theme#297]
I just installer paper theme on eos. Metacity works fine, but gtk looks broken :
![capture du 2016-04-16 18 08 46](https://cloud.githubusercontent.com/assets/7736765/14582180/57d38150-03fe-11e6-95f4-2d2f96b2c5eb.png)

**Comment by tim37021** [comment]
same here

**Comment by mfkr5** [comment]
The 1.0-0~147 works flawlessly ... On 2.0, color changes depending on the app (as expected) but windows decoration looks broken.

**Comment by snwh** [comment]
2.0 was a complete rewrite. I may have to investigate this on Freya(?)

**Comment by mfkr5** [comment]
That would be greatly appreciated :) It's an awesome theme.

**Comment by mfkr5** [comment]
Fixed with the latest daily build :)
