### ISSUE TITLE
Theme is broken on Ubuntu 15.10 + Cinnamon 2.8.6

### ISSUE THREAD

**Issue by byme8** [snwh/paper-gtk-theme#298]
I have installed Ubuntu 15.10 and found that theme is broke. 
On Ubuntu 14.04 LTS it works fine.

Ubuntu 15.10
![screenshot from 2016-04-16 20-39-33](https://cloud.githubusercontent.com/assets/5927686/14582656/f8642150-0413-11e6-8248-1704be8d8250.png)

Ubuntu 14.04
![screenshot from 2016-04-16 20 50 04](https://cloud.githubusercontent.com/assets/5927686/14582687/f7169d9a-0414-11e6-848e-bf3cd8ad2850.png)

**Comment by snwh** [comment]
Which version of the theme do you have?

**Comment by byme8** [comment]
Latest version from ppa:snwh/pulp on both(2.0+r201)
