### ISSUE TITLE
Corebird headerbar not correctly themed

### ISSUE THREAD

**Issue by HeikoAdams** [snwh/paper-gtk-theme#299]
On latest git master the headerbar of corebird is not correctly/completely themed
![bildschirmfoto von 2016-04-16 21-13-05](https://cloud.githubusercontent.com/assets/1418818/14583103/213559ce-0418-11e6-89e2-457675b7b6cf.png)

**Comment by snwh** [comment]
Which OS and version of corebird is this?

**Comment by HeikoAdams** [comment]
It's a Fedora 24 with Gnom 3.20 (GTK 3.20)

**Comment by jc00ke** [comment]
@HeikoAdams this goes away with later versions of corebird.

**Comment by HeikoAdams** [comment]
Yes, confirmed
