### ISSUE TITLE
gnome2 apps: titlebar seems to have 1 black pixel

### ISSUE THREAD

**Issue by sancio6** [snwh/paper-gtk-theme#3]
Hi! As promised, I'm here to write about gnome2 apps. 

I encountered just 1 issue: the titlebar seems to have, on the topleft, one black pixel (see attached screenshot). 

More, I must say that gnome 2 apps do not look so good with this theme, as the difference between titlebar and menubar can be a "punch on the nose". May I suggest to use, for them, the dark variant of the theme? 

![schermata da 2014-12-14 15 17 37](https://cloud.githubusercontent.com/assets/10185205/5427583/dc1e38dc-83a4-11e4-8fb8-7e9e65c2ff57.png)

**Comment by snwh** [comment]
I believe the latest commit has fixed this.

**Comment by poxip** [comment]
Works fine now (GNOME Shell 3.14.3).
