### ISSUE TITLE
GtkTreeView (gtk+-3.18.9) in Shotwell 0.22.0 rendering issue under new sass theme

### ISSUE THREAD

**Issue by ikelos** [snwh/paper-gtk-theme#302]
First-off, the new sass theme seems really slick, great work!  5:)

I noticed there's a slight issue with shotwell's GtkTreeView widget down the side, in that it seems to overpad the rows in some way?  It also happens (to a lesser extent) in the seahorse application (screenshots for both attached).  Please let me know if you need any more information/testing, I'd be happy to help, the paper theme is by far my favourite (even over adwaita).  5:)

![Shotwell sidebar GtkTreeView](https://cloud.githubusercontent.com/assets/1477845/14588609/58a38126-04c5-11e6-9dc1-38118f0e62f8.png)
![Seahorse (Passwords and Keys) GtkTreeView](https://cloud.githubusercontent.com/assets/1477845/14588608/58a3454e-04c5-11e6-9b7d-8b3479132440.png)

**Comment by alpapad** [comment]
Same behavior for nemo also, see #304

**Comment by ikelos** [comment]
Thanks, this appears to have been fixed in one of the very recent updates!  5:)

![screenshot from 2016-04-20 09-24-19](https://cloud.githubusercontent.com/assets/1477845/14667964/bc275f7c-06d9-11e6-89d9-3343473297f4.png)
