### ISSUE TITLE
All windows are basically broken.

### ISSUE THREAD

**Issue by DroWnThePoor** [snwh/paper-gtk-theme#306]
![screenshot from 2016-04-18 03 55 05](https://cloud.githubusercontent.com/assets/16339020/14597244/87471ea8-0519-11e6-9352-76f7754b45ea.png)

Since last update, dramatic change in theme, most programs look wrong now.
Also experiencing the "tree view" issue in Geary rather than Shotwell.

**Comment by snwh** [comment]
Oh man.

**Comment by DroWnThePoor** [comment]
I'm using the packaged ppa version, is there any way I can get back to where I was before these last two updates?

**Comment by Bifros7** [comment]
Happens to me too, using the 358.16 NVIDIA driver if it makes any difference.

**Comment by Monepone** [comment]
Same problem here on Elementary OS 0.3.2 (Ubuntu 14.04)

**Comment by snwh** [comment]
Is this still the case?

**Comment by Bifros7** [comment]
@snwh one of the updates you pushed the day I commented seemed to fix it for me.

**Comment by snwh** [comment]
@Bifros7 but. I didn't push any updates

**Comment by Monepone** [comment]
> Is this still the case?

The problem seems to be fixed! Thanks!
