### ISSUE TITLE
Bundle multiple GTK versions in same package

### ISSUE THREAD

**Issue by HEXcube** [snwh/paper-gtk-theme#311]
Since GTK 3.16, there can be multiple versioned theme folders. That is, there can be multiple directories named like `gtk-3.20`, `gtk-3.18`, `gtk-3.16`, etc instead of a single `gtk-3.0` directory. For example, GTK 3.20 will search for `gtk.css` in the directories `gtk-3.20`, ...,`gtk-3.14` and `gtk-3.0`. See: https://git.gnome.org/browse/gtk+/tree/gtk/gtkcssprovider.c#n2014

This is very useful for updating theme packages and adding support for new GTK versions without breaking previous ones. For eg: Ubuntu 16.04LTS provides GTK3.18 'out of box'. But some users upgrade to GTK3.20 from GNOME Staging PPA. With multiple versioned themes, there won't be a breakage anymore. :relaxed: 

However, there's a minor hurdle in the way: GNOME Tweak Tool 3.18 can't recognize versioned themes. :flushed: See these issues: https://github.com/tista500/Adapta/issues/40 , https://github.com/tista500/Adapta/issues/27 and https://github.com/solus-project/budgie-desktop/issues/405 . But it can be workarounded by providing `gtk-3.0` for GTK3.18 and versioned directories for GTK 3.20 and up. :relieved: That's how [Numix](https://github.com/shimmerproject/Numix) and [Adapta](https://github.com/tista500/Adapta) does it. It doesn't work if u wanna include GTK3.16 too, but most distros using it will get EOL'd in a few months, unlike GTK3.18 which's used by an LTS release (Ubuntu 16.04) and Solus 1.x.

**Comment by snwh** [comment]
Ah, more work.

**Comment by HEXcube** [comment]
But once you shift to multiple versions, it'll lessen the work! :grin: Coz, u won't have to deal with breakages due to GTK version mismatch. :relaxed:

**Comment by snwh** [comment]
Writing in all the support for all the GTK versions in this theme is getting tiresome.

**Comment by snwh** [comment]
If only I were clued into this before I rewrote the whole damn thing. Now I have to essentially re-rewrite.

**Comment by rusins** [comment]
Good thing you have the previous versions backed up in github, I assume.

**Comment by HEXcube** [comment]
No need to write new GTK theme, just keep one current GTK version -2 and one +2 themes in packages to ensure smooth updates and less breakages. :relaxed: Just bring back the GTK3.18 version like @rusins suggested

**Comment by snwh** [comment]
I could do that but  what I'm going to have to do is break apart the current mashed together theme into 3.18 & 3.20 and write in the 3.16 version. Since the rewrite also fixed many bugs in the previous versions.

**Comment by HEXcube** [comment]
But no distros using GTK3.16's gonna be supported that long. I don't know of any distro with GTK3.16 that's not gonna get EOL'd in a few months. :worried: I'll say it's too late to work on GTK3.16 now. GTK3.18 though is different case, with Ubuntu 16.04LTS (5 year support) and Solus 1.x (2 year support) using it. :relaxed:

**Comment by snwh** [comment]
You'd be surprised how long people linger on outdated distros.

**Comment by HEXcube** [comment]
K.. but once the support period's over you won't be able to push updates via PPAs and other repos. So, developing GTK3.16 seems a bit pointless this late in support cycle. :confused:

**Comment by snwh** [comment]
It'd be retroactive development. Trust me, people will be asking for it.

**Comment by HEXcube** [comment]
Well, then the workaround for GNOME Tweak Tool 3.18 and below'd have to be more complex! :open_mouth:

**Comment by snwh** [comment]
Okay, I've implemented the bundling. You folks should test it to see if bugs have been introduced.

**Comment by HEXcube** [comment]
Today I tested the new multiple versioned Paper from master branch on Ubuntu GNOME 16.04 Beta. I'm happy to let u know it's compatible with GNOME Tweak Tool 3.18. :smile:

However, the toggle buttons in Tweak Tool looks bigger than usual when using the theme from Github master. :worried: Looks fine with the PPA version though. What branch does the PPA version for 16.04 use? :confused:

**Comment by snwh** [comment]
@HEXcube what do you mean by bigger than usual? It's best to show me potential visual errors.

**Comment by HEXcube** [comment]
Oh shoot, I forgot to do screenshots! :flushed: I tested on my work machine at office. Will get 'em tomorrow :+1:

The PPA version was okay though. What's the difference between the two? Is the one in master not fully compatible with GTK3.18? :confused:

**Comment by snwh** [comment]
@HEXcube they are the same.

**Comment by HEXcube** [comment]
@snwh I just tested the two versions ([master](https://github.com/snwh/paper-gtk-theme/tree/master/) and `2.0+r204` from [PPA](https://launchpad.net/~snwh/+archive/ubuntu/pulp)) on **budgie-remix**.

I copied `gtk3.0` folder from **PPA version**, renamed it `gtk-3.18` and then replaced the one from `master`. The toggle button looks fine here! :relaxed: :

![paper from ppa on budgie](https://cloud.githubusercontent.com/assets/3755396/14652078/58be6c3a-0690-11e6-81d7-031f71c044c7.png)

Now, for the one in `master`, see the bigger sized buttons:

![paper on budgie](https://cloud.githubusercontent.com/assets/3755396/14652182/d8af99fa-0690-11e6-888b-522e1bb34429.png)

However, while I was testing the PPA got updated with a newer version `2.0+r210` derived from latest in `master` branch. I couldn't test it today. Will do that tommorow :relaxed:

**Comment by snwh** [comment]
Yes, the larger version is the intended size.

**Comment by snwh** [comment]
Paper doesn't have much of a Budgie theme, as you can see.

**Comment by HEXcube** [comment]
Well, I used Budgie just to show u the problem with toggle buttons. Didn't know big buttons were a new feature! :sweat_smile: Anyway, here are the screenshots with Tweak Tool on Ubuntu 16.04LTS's GNOME 3.18:

![Tweak Tool on Paper](https://cloud.githubusercontent.com/assets/3755396/14669460/9dd21094-0706-11e6-80a8-ebe3e043f65e.png)

![Tweak Tool on Paper Dark](https://cloud.githubusercontent.com/assets/3755396/14669473/a97c38c0-0706-11e6-89ec-4fa2a40f6455.png)

**Comment by HEXcube** [comment]
K... Now that Paper with multiple GTK theme versions are available in PPA and tested to work fine, shall I close this issue? :relaxed:
