### ISSUE TITLE
Files location/view options dropdown white letters on white background

### ISSUE THREAD

**Issue by bacsubtilis** [snwh/paper-gtk-theme#314]
Ubuntu 16.04 (paper 2.0+r210~daily~ubuntu16.04.1)

**Comment by bacsubtilis** [comment]
You are right! Sorry for not providing in the first place.
![20160421_203844](https://cloud.githubusercontent.com/assets/18569501/14718929/fef2cad4-0801-11e6-8564-46ec14a86658.jpg)

Sorry for the bad quality (picture taken from mobile phone), as a funny thing happens. When the menu/dropdown is open I cannot print the screen (take a snapshot).

Many thanks for the great theme btw

**Comment by Defman21** [comment]
>When the menu/dropdown is open I cannot print the screen (take a snapshot).

Open Screenshot Tool and set a delay.

**Comment by bacsubtilis** [comment]
Issue closed with the new update!

Many thanks again and to @Defman21 for the nice tip!

![screenshot from 2016-04-24 23-25-13](https://cloud.githubusercontent.com/assets/18569501/14770211/8df71536-0a74-11e6-900b-dcd7bb78c3d5.png)
Keep up the good work!
