### ISSUE TITLE
Top window too light

### ISSUE THREAD

**Issue by bobadigo** [snwh/paper-gtk-theme#317]
I installed paper like an hour ago, and im really liking it, but i have an issue! The bar of the first window, the one that im using, is too light, and that make the title hide, how can i fix it?
<a href="http://tinypic.com?ref=2pq12kl" target="_blank"><img src="http://i65.tinypic.com/2pq12kl.png" border="0" alt="Image and video hosting by TinyPic"></a>

P.S. I'm running Arch Linux with GNOME

**Comment by snwh** [comment]
@bobadigo which GNOME version or OS are you usign paper on? `gnome-shell --version` in a terminal will tell you.

**Comment by bobadigo** [comment]
GNOME Shell 3.20.1

**Comment by snwh** [comment]
Okay, I've not had a chance to fully debug the 3.20 version of paper.

**Comment by bobadigo** [comment]
What shoul i do?

**Comment by snwh** [comment]
Umm, you could wait until I get an opportunity to bug fix the 3.20. 

You can help to expedite that by (installing and) running `gtk3-widget-factory` to get the theme debug output and pasting that somewhere for me to look at.

**Comment by bobadigo** [comment]
I'm in this window right now, but don't know what to do to help you...
<a href="http://tinypic.com?ref=2wlugaq" target="_blank"><img src="http://i63.tinypic.com/2wlugaq.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by snwh** [comment]
@bobadigo I meant the terminal output. :P since that shows me all the error messages.

**Comment by bobadigo** [comment]
The problem is that, how can i get the output? Sorry for the wasting of time but I'm a new Linux user (downloaded and installer arch like 2 days ago).

**Comment by snwh** [comment]
@bobadigo and Arch is where you started? 

Running `gtk3-widget-factory` in a terminal will show a bunch of text (errors, warnings, etc), that would be  the output.

**Comment by bobadigo** [comment]
Yes, that was a bit mad to start directly from Arch, but i just wanted to try out something different :)

Anyway, i didnt notice the terminal output, but i already got it, sorry for the inconvenience.. Thats it:
<code>
[bobadigo@arch ~]$ gtk3-widget-factory

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk-dark.css:90:25: The style property GtkPaned:handle-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3132:32: The style property GtkLevelBar:min-block-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3133:33: The style property GtkLevelBar:min-block-height is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3208:34: The style property GtkLevelBar:min-block-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3209:35: The style property GtkLevelBar:min-block-height is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk.css:90:25: The style property GtkPaned:handle-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk.css:3140:32: The style property GtkLevelBar:min-block-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk.css:3141:33: The style property GtkLevelBar:min-block-height is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk.css:3216:34: The style property GtkLevelBar:min-block-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(gtk3-widget-factory:1124): Gtk-WARNING **: Theme parsing error: gtk.css:3217:35: The style property GtkLevelBar:min-block-height is deprecated and shouldn't be used anymore. It will be removed in a future version
</code>
 
Hope i helped you :)

**Comment by snwh** [comment]
Well it doesn't help with your bug, but thanks. :)

**Comment by bobadigo** [comment]
I'm sorry, but still hope that you can fix it..

If i can afk.. Is there a method to know if there is a new update without checking for a new version each time downloading the tarball from your site?

**Comment by snwh** [comment]
There's likely to be a package for it in the Arch User Repository.

**Comment by bobadigo** [comment]
Thanks for your patience and help! :)
