### ISSUE TITLE
Nautilus progress icon not visible

### ISSUE THREAD

**Issue by DSchmidtDev** [snwh/paper-gtk-theme#323]
I'm on Fedora 23 with Gnome Shell 3.18.4 and latest theme version from github

When there is something copied the progress circle in the header bar is only visible when hovering over it. 

edit: 
it's maybe not complete invisible but really dark. So it's hard to recognize, see picture attatched

![screenshot from 2016-04-24 17-02-30](https://cloud.githubusercontent.com/assets/11814088/14768434/579af732-0a42-11e6-9335-9b35e1b9606d.png)

**Comment by snwh** [comment]
I've noticed this. I'm not sure what to do about this.
