### ISSUE TITLE
Font Contrast

### ISSUE THREAD

**Issue by lakerssuperman** [snwh/paper-gtk-theme#329]
I really like the them and find it very complete.

My one issue, and this could come down to personal preference, is that the font color is too light on most backgrounds.  I see that it matches the other light gray used in the title bars, but I find my eyes straining to read the text because it is very gray and the background color in a lot of places isn't enough of a contrast to make it easily stand out like a darker black font would.

Continue the great work.

**Comment by snwh** [comment]
Which font?

**Comment by lakerssuperman** [comment]
The standard system font.  It's most obvious in programs like Nautilus.  On the left pane against the subtle gray shading the gray font starts to blend.  Even on the white background of Nautilus, the gray font seems somewhat washed out and my eyes don't focus on the text as easily as they do with other themes that use black font.

I also notice it programs like Firefox and Evolution that have a lot of gray shades.  For me at least, the gray font starts to blend into the other gray shades.

Maybe it's something I'll get used to running the theme more.  It doesn't make anything unusable, just for my eyes not as ideal as black font.
![paper theme](https://cloud.githubusercontent.com/assets/18699905/14861602/faa62ce0-0c7b-11e6-8f5b-e651f8e9739c.png)
![adwaita theme](https://cloud.githubusercontent.com/assets/18699905/14861618/022dd80a-0c7c-11e6-8945-2c4002e09c2b.png)

I attached screenshots.  One is with Paper and one is with the default Adwaita theme in Gnome Shell.  The black font in Adwaita feels so much easier to track and locate compared to the more gray font.

I hope I'm making sense lol.

Thanks.

**Comment by snwh** [comment]
I see your point. I've darkened the foreground/text colour (not all the way to black) to a darker grey #33333

**Comment by lakerssuperman** [comment]
Very cool.  I'll be sure to give it a try.  Thank you.

**Comment by lakerssuperman** [comment]
Readability is much improved.  Thank you!
