### ISSUE TITLE
Light version of Paper theme

### ISSUE THREAD

**Issue by Ilufirion** [snwh/paper-gtk-theme#331]
hi, what are the chances of getting a light (white colors) of the Paper theme in Ubuntu with Unity?
I really do like the light colors of the Radiance theme but I'm also a big fan of the Material design used in Paper.

**Comment by snwh** [comment]
First, the Paper theme isn't Material design. ;)

Your request would require me to essentially develop a whole extra theme, and I try to keep the amount of maintenance I have to do on Paper to a minimum, so there's no plans to make a light theme.
