### ISSUE TITLE
No colour for window title bars (all show up grey)

### ISSUE THREAD

**Issue by asclepius** [snwh/paper-gtk-theme#336]
Gnome 3.20
Arch Linux
Tried paper from AUR - paper-gtk-theme-git 244.de443e3-1
Also attempted fresh from git hub master: https://github.com/snwh/paper-gtk-theme/commit/1c81a528f5eb7e13221b0ca0a417aa30362b5e00

**Comment by snwh** [comment]
Sadly, changes in 3.20 put an end to the colourful header/title bars in Paper. To be fair, they were very hack-y to begin with.

**Comment by nicoulaj** [comment]
Is this definitive ?

**Comment by snwh** [comment]
@nicoulaj for 3.20 yes.

**Comment by StormBurpee** [comment]
@snwh It appears the System Monitor on Gnome 3.20 is still supporting the coloured header as it is green? Any reason as to why this might be - and if this could be implemented into the other apps..?

**Comment by JLCCI** [comment]
Since multiple colours are not an option anymore, is it possible to modify the one that is currently showing? It's not bad but I would really like to set it to be the same as the Paper shell top bar.

Thanks in advance.

**Comment by snwh** [comment]
Closing because it can't be fixed.
