### ISSUE TITLE
Guake Active Tab

### ISSUE THREAD

**Issue by edomos** [snwh/paper-gtk-theme#339]
When I'm using Guake with Paper Theme I cant see active tab
Paper theme example:
![image](https://cloud.githubusercontent.com/assets/9549383/14959978/986c3d60-1092-11e6-9a0e-7537a4228468.png)
Ambiast Theme example:
![image](https://cloud.githubusercontent.com/assets/9549383/14959989/aced10b6-1092-11e6-86b8-e4a1e1d47017.png)

**Comment by snwh** [comment]
Strange that Guake uses buttons for tabs instead of tabs.

**Comment by edomos** [comment]
Yeah, its strange. So, can you active button color to your theme?
