### ISSUE TITLE
Not a issue but... 

### ISSUE THREAD

**Issue by luigimassa** [snwh/paper-gtk-theme#343]
Hi, 
I installed paper theme.
Wow fantastic.
In past I donate some money for this project

Now I'm interested to help to develop and resolve issues

How can I help? Where can I start?
thanks in advance

**Comment by snwh** [comment]
Well, of the 100+ bugs in the Paper theme, you can try to fix one of those and submit a pull request.

**Comment by snwh** [comment]
(I'm going to close this as it's not really an issue).
