### ISSUE TITLE
The window disappeared when I double clicked the title bar.

### ISSUE THREAD

**Issue by mopperwhite** [snwh/paper-gtk-theme#344]
The window just ... minimized. Only title bar was left for seconds. 

It won't happen if I click the maximized button.

And it seems that such a thing doesn't happen on dialogs.

In fact, it happens on:
* gnome-terminal
* nautilus
* brackets

not on:
* gnome-control-center
* gnome-screenshot
* gnome-tweak-tool

I'm not sure but I think such problem started since I updated my system this noon and paper-gtk-theme might be installed during it.

* Unity version: 8.02+15.04.20150409.1-0ubuntu1
* linux: Ubuntu 15.04
* paper-gtk-theme version: 2.0+r226~daily~ubuntu15.04.1

I'm sorry for not providing a screenshot, but the window just ... disappeared.

**Comment by snwh** [comment]
Can you confirm this is a problem with the Paper theme by testing this with other themes?

**Comment by mopperwhite** [comment]
@snwh 
Good idea... I didn't even think about it ...

Okay... seems that the problem is not caused by paper-theme-gtk ...

Sorry ... my bad ...

**Comment by snwh** [comment]
Usually bizarre things like this are unrelated to themes ;)
