### ISSUE TITLE
gtk+-3.18 titlebar size discrepancy

### ISSUE THREAD

**Issue by ikelos** [snwh/paper-gtk-theme#346]
Hiya,

Not sure when this started, I think it's been a while, but under the latest version of the theme (as of today), the titlebar on gtk+-3 apps can be different heights based on whether they contain controls or not (compare gnome-terminal with gedit).  I'm happy to accept this could entirely be an opinion piece, but if not then it would be nice to make them all the thicker size (which might also help resolve some of the "buttons too small" issues).

![screenshot from 2016-05-09 15-17-42](https://cloud.githubusercontent.com/assets/1477845/15125397/96e45b7c-15fa-11e6-885e-46d42c93cd29.png)

**Comment by snwh** [comment]
This difference is that some windows use headerbars and some do not.

**Comment by ikelos** [comment]
Ah, that does seem to happen on the default theme as well.  Sorry, my bad.
