### ISSUE TITLE
Libre Office menu/icons area are incorrectly colored.

### ISSUE THREAD

**Issue by bhajneet** [snwh/paper-gtk-theme#360]
- the GNOME/GTK version that is on your system
GNOME Shell 3.20.2
GTK+ Paper/Arc

- which Linux distribution you are running
Arch Linux 4.5.4-1

- the version of Paper you are using
Idk how to find this

Most importantly: please attach a screenshot of your issue, a visual bug needs to be seen

With Paper GTK+
![screenshot from 2016-05-26 16-37-37](https://cloud.githubusercontent.com/assets/14130567/15589431/d480b99e-2360-11e6-8a3a-bcf04be3da74.png)

With Arc GTK+
![screenshot from 2016-05-26 16-38-38](https://cloud.githubusercontent.com/assets/14130567/15589430/d48048ba-2360-11e6-80ee-9c591760cdf2.png)

**Comment by snwh** [comment]
Hmm.

**Comment by snwh** [comment]
Libreoffice is a pain point because it mixes so many different widgets (that have different themes) and it also depends on whether or not it's using GTK2 or GTK3.

**Comment by towo** [comment]
Bump on this for Ubuntu 16.04 (GNOME 3.18, LibreOffice 5.1.3).

Had this issue for some time, though, so nothing new in that regard.

**Comment by 1Claude** [comment]
With Apricity OS (Arch based distro, Cinnamon, GNOME 3.20) I had issues with LibreOffice with almost any themes. Only the one from Apricity was OK.

**Comment by mmccoy37** [comment]
I have this issue as well. Does anyone know of a workaround?

**Comment by bhajneet** [comment]
Fixed by LibreOffice "fresh" version 5.2
