### ISSUE TITLE
Nautilus sidebar context menu mouseover highlight

### ISSUE THREAD

**Issue by lpinner** [snwh/paper-gtk-theme#364]
- Gnome 3.18.4
- Nautilus 3.14.3
- Ubuntu Gnome 16.04
- Paper 2.1+r262~daily~ubuntu16.04.1

Mouseover highlight is not shown/white in Nautilus sidebar context menu so white text is not readable.. In screenshot below, mouse is over the 2nd entry "Open in New Tab".

![screenshot from 2016-06-04 08-03-07](https://cloud.githubusercontent.com/assets/4827816/15794201/81905f1e-2a2c-11e6-92ca-1e173adb4426.png)

**Comment by lpinner** [comment]
Same issue on Solus OS with Nautilus 3.18.5 and [Paper 2.1.0](https://git.solus-project.com/packages/paper-gtk-theme)

**Comment by 1Claude** [comment]
I don't have that issue, same Ubuntu.
![paper issue](https://cloud.githubusercontent.com/assets/19640810/15847335/136ebcd2-2c53-11e6-8393-1c439a47bbba.png)

**Comment by lpinner** [comment]
@1Claude is your mouse over any of the entries in the context menu?

**Comment by 1Claude** [comment]
@lpinner Ah... You're right. Mouse over, it becomes blank.

**Comment by lpinner** [comment]
Project appears abandoned #462
