### ISSUE TITLE
Failed buiding from AUR

### ISSUE THREAD

**Issue by germanfr** [snwh/paper-gtk-theme#365]
I downloaded the [paper-gtk-theme-git](https://aur.archlinux.org/packages/paper-gtk-theme-git) from the AUR but the build fails. It says:

```
==> Starting pkgver()...
==> Updated version: paper-gtk-theme-git 297.06fb8b4-1
==> Starting build()...
/tmp/yaourt-tmp-german/aur-paper-gtk-theme-git/ ./PKGBUILD: ./autogen.sh: /bin/sh^M: bad interpreter: no such file or directory
==> ERROR: A failure occured in build().
Aborting....
==> ERROR: Makepkg was unable to build paper-gtk-theme-git.
```

GTK version: 3.20.6-1 (I think)
I am running Manjaro Cinnamon 3.0.4.

**Comment by steffinger** [comment]
This is definitly not the right place to complain about a not working distro package. I would suggest, you close this issue and contact your Manjaro package maintainer. 

BTW: I'm using Archlinux, and the package (Same build number) builds just fine for me. And you should think twice before using yaourt over the standard makepkg way. yaourt brings an extra layer of possible failures.

**Comment by germanfr** [comment]
Sorry, I thought it was a repo problem. As it says git, I thought all the build files were in the repo and it was being built from there.

PS: I don't even know what yaourt is. I just installed it from the package manager :)

**Comment by germanfr** [comment]
This is the same issue as snwh/paper-icon-theme#440

Please, don't let GitHub automatically convert your bash files to CRLF.
