### ISSUE TITLE
Installing Update Freezes Elementary OS

### ISSUE THREAD

**Issue by TristanWiley** [snwh/paper-gtk-theme#368]
I'm running elementary OS 0.3.2 Freya (64-bit) on my HP 15z-af100 laptop.  
I was trying to update/install the latest version when I saw the update was avalible (unsure the number) and whenever it was unzipping xxxxx over xxxxx it froze and I couldn't move my mouse or anything on my screen.  Pressing F1/F2 did nothing and the only way to fix was to reboot manually.

```
Processor: Quad-Core AMD A8-7410 APU with AMD Radeon R5 Graphics
Memory: 3.3 GiB
Graphics: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 45)
Storage: 165.0 GB
```
At the point in the screenshot below my computer was completely unresponsive and I had to take a picture with my phone.  (I had force removed Paper after it broke so this is different than when it updated. Still the same problem.)

![Issue. If you see this hi.](https://cloud.githubusercontent.com/assets/2747793/15879728/a7b22a36-2cf4-11e6-9df9-ace835900bd8.jpg)

**Comment by snwh** [comment]
I think you mean to file against the icon theme. I think this is the same issue: https://github.com/snwh/paper-icon-theme/issues/228

**Comment by TristanWiley** [comment]
Apologies for that.

**Comment by snwh** [comment]
@TristanWiley no worries. You're not the first (nor the last) ;)
