### ISSUE TITLE
HOW TO install paper theme in ubuntu

### ISSUE THREAD

**Issue by sakshamgoyal01** [snwh/paper-gtk-theme#373]
I AM LITERALLY COMPLETE NOOB. I JUST DOWNLOADED UBUNTU 10MINS AGO. 
how do i install the paper theme?
i ran the script through the terminal but nothing happened after that:
`sudo add-apt-repository ppa:snwh/pulp
sudo apt-get update
sudo apt-get install paper-icon-theme
sudo apt-get install paper-gtk-theme`

what do i do next?

**Comment by snwh** [comment]
You'll need an app like GNOME Tweak Tool or Unity Tweak Tool to change your icon theme or in the terminal you can go:

    gsettings set org.gnome.desktop.interface icon-theme "Paper"
    gsettings set org.gnome.desktop.interface gtk-theme "Paper"
    gsettings set org.gnome.desktop.wm.preferences theme "Paper"

**Comment by sakshamgoyal01** [comment]
i am using ubuntu

**Comment by snwh** [comment]
Same instructions

**Comment by sakshamgoyal01** [comment]
can you give me a link to download and exactly what to do? thanks

**Comment by snwh** [comment]
The download page is here: https://snwh.org/paper/download but the process is still the same.

**Comment by sakshamgoyal01** [comment]
i meant for downloading the tweak tool. i searched it online.... i dont understand what to do. thanks

**Comment by sakshamgoyal01** [comment]
i ran this in the terminal, then it asked for my password. then it came with an error.... i ran this:
sudo apt-get install unity-tweak-tool gnome-tweak-tool

**Comment by snwh** [comment]
You weren't lying about being a complete noob.

**Comment by snwh** [comment]
The terminal is a keyboard interface (no clicking) you use Tab and the arrow keys to navigate.

**Comment by sakshamgoyal01** [comment]
thank you so much
