### ISSUE TITLE
Nautilus window strange white borders

### ISSUE THREAD

**Issue by Alabme** [snwh/paper-gtk-theme#374]
There are some strange white borders wrapping nautilus window/

- GTK:  3.18.9-1ubuntu3
- ubuntu 16.04
- paper-gtk-theme version: 2.1.0

Screenshot:
![nautilus-strange-borders](https://cloud.githubusercontent.com/assets/2773776/16076052/d70b1b14-32f1-11e6-9dba-3c3cd450dd9a.jpg)

**Comment by Alabme** [comment]
It seems it is connected with nautilus itself. I'm closing it.

**Comment by snwh** [comment]
I love these self-resolving issues. ;)

**Comment by smaznet** [comment]
@Alabme 
How you fix this?

**Comment by Alabme** [comment]
@smaznet 

I don't. It is still there, but right now i'm not sure is it nautilus, duplication of https://github.com/snwh/paper-gtk-theme/issues/262 issue, or both?
