### ISSUE TITLE
Emacs highlighting color

### ISSUE THREAD

**Issue by ChillarAnand** [snwh/paper-gtk-theme#377]
```
→ dpkg -l libgtk2.0-0 libgtk-3-0

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                            Version              Architecture         Description
+++-===============================-====================-====================-===================================================================
ii  libgtk-3-0:amd64                3.18.9-1ubuntu3      amd64                GTK+ graphical user interface library
ii  libgtk2.0-0:amd64               2.24.30-1ubuntu1     amd64                GTK+ graphical user interface library

→ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

→ uname -a
Linux laptop 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Paper I have using master branch from github.

While using default ubuntu theme, I i highlight text in emacs editor, it shows like this

![aa](https://cloud.githubusercontent.com/assets/4463796/16480829/f1de83b0-3ec5-11e6-9e25-df72686831bf.png)

After installing paper, it became like this

![pp](https://cloud.githubusercontent.com/assets/4463796/16480845/05f2b4ca-3ec6-11e6-9f62-2808273eef00.png)

I thought it was emacs error and tried fixing it. After a while, after looking closely at above pic, it looks like paper is highlighting in white color.

Can you tell me how to fix/change this?

Thank you.

**Comment by wbolster** [comment]
i don't really understand your problem. is this about an emacs theme?  if so, you're at the wrong place. ;)
