### ISSUE TITLE
No colourful headers on Gnome 3.20

### ISSUE THREAD

**Issue by WantedFish** [snwh/paper-gtk-theme#380]
- GNOME/GTK version: 3.20
- Linux distribution: Ubuntu 16.04
- the version of Paper: Latest

Having colourful (colorful) headers on Gnome 3.18.
But no colourful (colorful) headers on Gnome 3.20.

Please check about it.

**Comment by ikelos** [comment]
This is a duplicate of issue #336.  Please look through old issues before filing new ones...

**Comment by WantedFish** [comment]
really sad :'(
