### ISSUE TITLE
Please HELP me

### ISSUE THREAD

**Issue by WantedFish** [snwh/paper-gtk-theme#381]
- GNOME/GTK version: 3.20
- Linux distribution: Ubuntu 16.04
- Version of Paper: Latest

I know that Paper theme haven't colourful (colorful) header/title bars.
But,
Please teach me to change the colors of header/title bars in Gnome 3.20.
Please give me the style-class belongs to colours of title bars.

Thanks.

**Comment by ikelos** [comment]
The techniques that paper-gtk-theme used to alter the colours of titlebars were removed **by the gnome developers** from gnome 3.20 itself (not from the paper theme), as was mentioned in issue #336, which you were already told about in #380.

Please do not open more issues about the same topic particularly when you've already been told they are duplicates.  I'm sorry you're sad, many of us are, but filing issue after issue on this bug tracker will not achieve your goal.

**Comment by WantedFish** [comment]
OK.
