### ISSUE TITLE
Menu texts hidden in some apps

### ISSUE THREAD

**Issue by terencode** [snwh/paper-gtk-theme#385]
Hi! 
First of all this is one of my favorite GNOME theme keep up the good work ^.^
Second, I noticed that the theme hides partially or totally the text on the menu on some apps which can be really annoying...

Examples in the screenshot below:

![paper_screenshot](https://cloud.githubusercontent.com/assets/12665563/16960069/23bb04a4-4de8-11e6-995b-a3b4ce50eaf3.png)

My config:
*GNOME 3.20.2 / gtk3 3.20.6-1
Arch Linux 4.6.4-1
paper 299.cecb923-1*

Thanks!

**Comment by wbolster** [comment]
same here. gnome 3.20 on ubuntu. application bijiben for instance:

![image](https://cloud.githubusercontent.com/assets/748944/16964709/2aa73f7a-4dfd-11e6-9bff-177d6156e3f1.png)

**Comment by tmsimont** [comment]
Same problem here.

GTK+ Version 3.209
GDK Backend X11

![screenshot from 2016-09-11 09-40-32](https://cloud.githubusercontent.com/assets/1643712/18418443/d2a1a69a-7803-11e6-97ae-23dec78240ae.png)

The problem does not exist for the dark theme variant

**Comment by tmsimont** [comment]
I looked at it with gtk-inspector and it seems like it could be related to the fact that headerbar css is overriding the menu label:

```
    headerbar button label,
    headerbar button image {
      color: #ffffff; }
```
Since the menuItem is in the headerbar, it gets set to `#ffffff` color

This comes from 

`widgets/_header-bars.scss`

It's probably just a matter of putting some kind of priority on the `menuItem` css rule.

**Comment by tmsimont** [comment]
#397 seems to fix it, but you'll have to re-parse sass. I have not seen any negative side effects of removing that selector

**Comment by terencode** [comment]
Thanks, it fixes it.
