### ISSUE TITLE
Kubuntu issue

### ISSUE THREAD

**Issue by dann95moz** [snwh/paper-gtk-theme#394]
Hi, im trying to install paper on Kubuntu the icon theme is working perfectly but the the GTK theme is not showed on the theme list , i tried to install it split but still not working, is not working actually on kde?

**Comment by Narrat** [comment]
In general KDE uses the QT Toolkit, whereas Paper is for the GTK-Toolkit (used for example by GNOME).
It can only be achieved, that GTK Programs, that you want to use under KDE, use the theme
