### ISSUE TITLE
Style properties name that were deprecated - Warnings while plotting

### ISSUE THREAD

**Issue by JLCCI** [snwh/paper-gtk-theme#402]
I'm using Gnome 3.20 with newest paper theme. When I plot in Python I get the following errors:

Gtk-WARNING **: Theme parsing error: gtk-dark.css:90:25: The style property GtkPaned:handle-size is deprecated and shouldn't be used anymore. It will be removed in a future version

Gtk-WARNING **: Theme parsing error: gtk-dark.css:3209:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

Gtk-WARNING **: Theme parsing error: gtk-dark.css:6352:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

Gtk-WARNING **: Theme parsing error: gtk-dark.css:6362:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

Gtk-WARNING **: Theme parsing error: gtk-dark.css:6525:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

Gtk-WARNING **: Theme parsing error: gtk-dark.css:6548:52: The :prelight pseudo-class is deprecated. Use :hover instead.

I encountered the same type of error with Numix (although just 1) and that was fixed by renaming the properties to newer names.

**Comment by Narrat** [comment]
Just want to note, this stuff was already reported. See #350

**Comment by JLCCI** [comment]
Great, thanks. I will leave this open as I got two additional warnings that were not present in previous previous report.

Gtk-WARNING **: Theme parsing error: gtk-dark.css:6352:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

Gtk-WARNING **: Theme parsing error: gtk-dark.css:6548:52: The :prelight pseudo-class is deprecated. Use :hover instead.

**Comment by JLCCI** [comment]
Apologies it was mentioned in another post.
