### ISSUE TITLE
Problems in Linux Mint 13 / Precise Pangoline Ubuntu 12.04

### ISSUE THREAD

**Issue by gianlucarenzi** [snwh/paper-gtk-theme#408]
Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita", at /usr/share/perl5/Debconf/FrontEnd/Gnome.pm line 111, <> line 2.
/usr/share/themes/Paper/gtk-2.0/main.rc:726: error: unexpected identifier `direction', expected character`}'
/usr/share/themes/Paper/gtk-2.0/apps/chrome.rc:50: error: invalid string constant "button", expected valid string constant

Adwaita SHOULD be installed, as I have more themes with this engine. If not, where I have to check??

I am using PaperThem from repo. So I suppose it is the latest released.

Best Regards,

**Comment by wellington1993** [comment]
Hi,

Did you already tried `sudo apt install gnome-themes-standard` to try solve this?

Bye.

**Comment by snwh** [comment]
Sorry, Ubuntu 12.04 is far too old a release for Paper.
