### ISSUE TITLE
Installation Issue on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by kelunik** [snwh/paper-gtk-theme#421]
Currently I can't install `paper-gtk-theme` because of unmet dependencies. Previously I had it installed, but it has been uninstalled by an update and I missed it in the list of packages to be removed.

```
LANG=en_US.UTF-8 sudo apt install paper-gtk-theme
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 paper-gtk-theme : Depends: gtk2-engines-pixbuf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

```
$ LANG=en_US.UTF-8 sudo apt install gtk2-engines-pixbuf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gtk2-engines-pixbuf : Depends: libgtk2.0-0 (= 2.24.30-1ubuntu1) but 2.24.30-1ubuntu1.16.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I guess this is an issue with `libgtk2.0`, no? _"gtk2-engines-pixbuf : Depends: libgtk2.0-0 (= 2.24.30-1ubuntu1) but 2.24.30-1ubuntu1.16.04.1 is to be installed"_ seems strange.

**Comment by KennyClark7** [comment]
i have the same Error but not with the paper-gtk-theme. it is with the macbuntu 16.04. i got this error
>Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
macbuntu-os-icons-lts-v7 is already the newest version (3.18.10~xenial~NoobsLab.com).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

>The following packages have unmet dependencies:
 macbuntu-os-ithemes-lts-v7 : Depends: gtk2-engines-pixbuf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

then i tried to install gtk2-engines-pixbuf

>kenichi@kenichi-Aspire-E5-473G:~$ sudo apt-get install gtk2-engines-pixbuf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

>The following packages have unmet dependencies:
 gtk2-engines-pixbuf : Depends: libgtk2.0-0 (= 2.24.30-1ubuntu1) but 2.24.30-1ubuntu1.16.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

i hope someone could enlighten us

**Comment by kelunik** [comment]
I solved it thanks to `geser` in `#ubuntu-packaging`.

It's due to `xenial-proposed` being only activated for `main`. You have to update your `/etc/apt/sources.list` and change `deb http://de.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted` to `deb http://de.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe`.

After that, `sudo apt update` and `sudo apt upgrade` and installation works fine.
