### ISSUE TITLE
Directory/file renaming color issue

### ISSUE THREAD

**Issue by thedevsaddam** [snwh/paper-gtk-theme#425]
### Icon Request

Please provide the following in your request:

- paper-icon-theme
- Icon=`not icon problem!`

When renaming a directory or file the text field background is white so the text can not be seen.
![screenshot from 2016-12-15 10-48-47](https://cloud.githubusercontent.com/assets/9676798/21212202/7f69e838-c2b4-11e6-8a42-7bbdb27b8115.png)

**Comment by alpapad** [comment]
And when the background of the application is white, the selected, highlighted entry for rename is not really visible.

I am using nemo and this happens in compact and icon view. I list view, there is a rectangle highlighting the entry.

**Comment by smaznet** [comment]
i have this issue on ubuntu 16.04

**Comment by ramundomario** [comment]
I also have this problem, it is really annoying...
