### ISSUE TITLE
[Antergos-Gnome 3.22.2] All window headers are same color

### ISSUE THREAD

**Issue by Momoe** [snwh/paper-gtk-theme#428]
Thank you for filing a bug against the Paper theme, however please try and provide the following information while doing so:

"I just installed the Paper GTK theme from the git repository, and none of the windows are colored differently. I'm wondering if there's something else needed for the colors to take affect?" 

- the GNOME/GTK version that is on your system
Gnome 3.22.2
- which Linux distribution you are running
Antergos
- the version of Paper you are using
paper-gtk-theme-git 301.f75724-f
Most importantly: please attach a screenshot of your issue, a visual bug needs to be seen

![](http://i.imgur.com/czLh0rS.png)

**Comment by nicoulaj** [comment]
see #336

**Comment by snwh** [comment]
Like I said in #366, it's impossible to have different coloured header bars in GTK 3.20 and beyond.
