### ISSUE TITLE
Tiny titlebar closing button on hidpi

### ISSUE THREAD

**Issue by aquatix** [snwh/paper-gtk-theme#44]
On hidpi, the buttons in the (non-unified) window titlebar are tiny. Please let those assets use the bigger versions too. See the terminal window in the screenshot.

![Tiny close button](https://cloud.githubusercontent.com/assets/629545/5523361/c71a7616-89c7-11e4-88b6-aac37e1ceff2.png)

This screenshot also shows the dotted-outline issues already mentioned in #42

**Comment by nlaplante** [comment]
:+1: I experience the same issue here.

**Comment by snwh** [comment]
Is this still occurring?

**Comment by aquatix** [comment]
Thanks for waiting, I was just now able to do some tests.

No, this is not occurring any longer, looking fine now! The theme generally looks great under Gnome 3.18.
