### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by viggy96** [snwh/paper-gtk-theme#446]
Is the Paper GTK theme abandoned? There hasn't been any commit activity in a while...

**Comment by snwh** [comment]
More or less

**Comment by snwh** [comment]
GTK theme development is too time consuming and keeping up with GTK releases is a bunch of work. I'd much prefer focusing on icons.

**Comment by viggy96** [comment]
Well, maybe that should be put on the readme and your website. A lot of other websites, like OMG Ubuntu, and webupd8 have articles about this theme which should be updated with this information.

**Comment by snwh** [comment]
It's not completely dead, it's just low priority.
