### ISSUE TITLE
Black areas on background windows during popups (Synaptic Package Manager)

### ISSUE THREAD

**Issue by michalsukupcak** [snwh/paper-gtk-theme#46]
Hi,

I've noticed this only in Synaptic:

When the main window looses focus to smaller popup, the original window goes a bit insane with black squares, see screenshot ... :)) This issue has been present ever since I've first installed the theme few days ago (didn't appear after last update).

![screenshot from 2014-12-23 16 28 51](https://cloud.githubusercontent.com/assets/5606432/5539485/6656bb40-8ac2-11e4-9ae4-4ee96edbd95a.png)

Info:
- Ubuntu GNOME 14.10 (amd64)
- Gnome Shell 3.14.2
- Synaptic 0.81.2
- Paper GTK 1.0-0~48~ubuntu14.10.1

p.s.: You need root access to use synaptic (ie. admin window prompt), don't know if its relevant, just mentioning it. If you need any additional information, just let me know, I'll be happy to provide whatever you need.

Regards,
Michael

**Comment by snwh** [comment]
This has been fixed for some time.
