### ISSUE TITLE
Transmission progress bar white-on-white

### ISSUE THREAD

**Issue by dehen** [snwh/paper-gtk-theme#48]
FYI, the progress bar in transmission is white except when hovering.

**Comment by paulhewson** [comment]
Yeah, same for me

**Comment by gmvelencoso** [comment]
Even in dark theme, the progress bar is same color as background. 
![screenshot from 2015-01-25 12 33 29](https://cloud.githubusercontent.com/assets/4999389/5891320/7615e1e2-a48e-11e4-9858-efd04d61135e.png)
