### ISSUE TITLE
Pane Separator in .titlebar

### ISSUE THREAD

**Issue by dehen** [snwh/paper-gtk-theme#49]
If the pane separator rises through the client side decorations .titlebar, as in Gedit's sidebar, the pane separator looks a little out of place for a flat theme. It has gradients and a gripper image.

![title separator](https://cloud.githubusercontent.com/assets/10331141/5564355/492ea264-8e76-11e4-8006-41ded9b59297.png)

I messed with it a bit and couldn't find the right properties, because I have no idea what I'm doing. But for now I'm using the following, which obviously isn't ideal:
.titlebar  { -GtkPaned-handle-size: 0; }

**Comment by snwh** [comment]
This has been slightly fixed

**Comment by snwh** [comment]
Actually I've fixed it now. ;)
