### ISSUE TITLE
Desktop Icons hard to read on Dark Backgrounds

### ISSUE THREAD

**Issue by eumario** [snwh/paper-gtk-theme#54]
When allowing Nautilus to utilize the File icons on the desktop, with dark backgrounds, the text is hard to read when the desktop is selected.  Adding the following to apps/nautilus.css:

.nautilus-desktop.nautilus-canvas-item {
    color: white;
    text-shadow: 1px 1px black;
}

Fixes the issue.

Before:
![darkbackgroundissue](https://cloud.githubusercontent.com/assets/63555/5608291/48dbf85c-944d-11e4-9e98-b9e4e25b7dc9.jpg)

After:
![darkbackgroundfixed](https://cloud.githubusercontent.com/assets/63555/5608292/523715ee-944d-11e4-9fab-f9f15fe8fd19.jpg)

**Comment by snwh** [comment]
Fixed in latest commit.

**Comment by eumario** [comment]
Works Great.  Thanks.
