### ISSUE TITLE
California title is not looking good

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-gtk-theme#56]
Hello, 
you can see that on the picture ive shared below 
![screenshot from 2015-01-06 13 37 39](https://cloud.githubusercontent.com/assets/7660997/5628558/4b9fa086-95a9-11e4-81a0-f73e1cb6c3af.png)
i'm talking about the date "Janvier 2015"
Hope you can fix it on the next commit ;)
Thanks!!

**Comment by sbaconnais** [comment]
Hello,

The problem remain on Ubuntu Gnome 15.04
![capture du 2015-09-08 13 34 06](https://cloud.githubusercontent.com/assets/5074414/9733769/4c0fcd34-562e-11e5-8cd0-1a735bf72eb7.png)
