### ISSUE TITLE
Some little improvements 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-gtk-theme#57]
Hello, i ve been using Paper since the first day i knew about it,
so i ve made a list of some bugs/corrections
I'm using Gnome shell 3.14.3

this one in settings, i hope you can add a border(so we can see better the search field?) 

![screenshot from 2015-01-06 13 47 13](https://cloud.githubusercontent.com/assets/7660997/5628657/8ac30bda-95aa-11e4-9be3-9cc66bcbe9b1.png)
the font color of the "air plane mode" isnot so visible ? maybe a white one would be nice! 
![screenshot from 2015-01-06 13 49 25](https://cloud.githubusercontent.com/assets/7660997/5628686/d756939a-95aa-11e4-8629-1469d072d904.png)
the off/on button when you dont have a bluetooth device in your laptop !
![screenshot from 2015-01-06 13 50 58](https://cloud.githubusercontent.com/assets/7660997/5628700/20a2da18-95ab-11e4-94d3-dad175752e3a.png)
the date widget font color is not visible at all
![screenshot from 2015-01-06 13 52 31](https://cloud.githubusercontent.com/assets/7660997/5628712/4951990e-95ab-11e4-8404-55139390593f.png)
the weather apps (gnome weather); as you see the font color problem again
![screenshot from 2015-01-06 13 55 03](https://cloud.githubusercontent.com/assets/7660997/5628741/a11d0178-95ab-11e4-94d9-b5766c730afe.png)

That's all! if i found something else i would be happy to report it ;)
Thank you

**Comment by bil-elmoussaoui** [comment]
need some imporvements to the Geray mail app! as you can see, the same text color bug,also for the buttons(the text is white)
![screenshot from 2015-01-06 19 47 47](https://cloud.githubusercontent.com/assets/7660997/5634048/ea5bc384-95dc-11e4-9d61-9f6c020b7708.png)
The same thing for the gnome contacts (the search field text color)
![screenshot from 2015-01-06 19 49 16](https://cloud.githubusercontent.com/assets/7660997/5634073/1c9ad9a2-95dd-11e4-9b92-f72f904cec87.png)

**Comment by bil-elmoussaoui** [comment]
up?

**Comment by snwh** [comment]
I think most of these are fixed, if not refile as separate bugs.
