### ISSUE TITLE
active partition not visible in gnome disks

### ISSUE THREAD

**Issue by underdoeg** [snwh/paper-gtk-theme#58]
The selected partition is not visible in gnome disks. Looks like it has a white font with a white background.

![120 gb disk_203](https://cloud.githubusercontent.com/assets/243820/5633109/72cd0f92-95d4-11e4-98a1-6aa2aa9e6dca.png)
![120 gb disk_204](https://cloud.githubusercontent.com/assets/243820/5633111/771a2738-95d4-11e4-8ba4-76bbc6bc0d89.png)
![1 0 tb hard disk_205](https://cloud.githubusercontent.com/assets/243820/5633113/7d703924-95d4-11e4-8f17-4cbd9bfa21ec.png)

when the window is not focus however the partition appears in a light grey
![1 0 tb hard disk_207](https://cloud.githubusercontent.com/assets/243820/5633117/8c3d57b6-95d4-11e4-9531-2bce79b7519c.png)

This is on arch linux, gtk 3.14

**Comment by enake** [comment]
Same issue on Ubuntu 14.10
![screenshot from 2015-01-14 17 46 09](https://cloud.githubusercontent.com/assets/6717006/5741673/4e7d3634-9c15-11e4-9cf0-d474b94db7c3.png)

**Comment by region51** [comment]
Yet to Be Decided
![2015-03-04 14 52 12](https://cloud.githubusercontent.com/assets/10940138/6483255/e8df38a4-c27f-11e4-9b6d-85ab0c863ba0.png)

**Comment by snwh** [comment]
I've been attempting to fix this for awhile.

**Comment by region51** [comment]
@snwh , So Much Better
![2015-03-12 22 33 19](https://cloud.githubusercontent.com/assets/10940138/6626517/2efe0f66-c908-11e4-86ba-0c22d0bdf806.png)

**Comment by underdoeg** [comment]
awesome
