### ISSUE TITLE
Close side pane button in Evince is not visible

### ISSUE THREAD

**Issue by swarnendubiswas** [snwh/paper-gtk-theme#68]
The close side pane button in Evince is not visible, unless it is focused. The following are two screenshots to show the problem.

![screenshot from 2015-02-01 23 08 02](https://cloud.githubusercontent.com/assets/7343807/5995688/dce80d44-aa67-11e4-96a9-9367c1be7336.png)

![screenshot from 2015-02-01 23 07 55](https://cloud.githubusercontent.com/assets/7343807/5995691/e48b0c36-aa67-11e4-9fdf-e1e146067905.png)

**Comment by snwh** [comment]
This is fixed since the theme no longer looks like this.
