### ISSUE TITLE
Pamac progress counter erased

### ISSUE THREAD

**Issue by Polochamps** [snwh/paper-gtk-theme#72]
Pamac progress counter (numeric) gets erased when the progess bar passes through.

**Comment by snwh** [comment]
Please include a screenshot or provide more info

**Comment by Polochamps** [comment]
Here it is buddy.
Thank you
![test](https://cloud.githubusercontent.com/assets/10701018/6193739/337fbdb0-b3f9-11e4-81f5-c2df405f710e.png)
