### ISSUE TITLE
text color hard to read

### ISSUE THREAD

**Issue by beavermml** [snwh/paper-gtk-theme#73]
using Elementary OS Luna ( 0.2 )..

text color in files are 99% transparent ( or blend with background )
![screenshot from 2015-02-12 12 59 21](https://cloud.githubusercontent.com/assets/3795219/6162061/13c0d948-b2b7-11e4-8c82-2f9b5c6ff5f9.png)

**Comment by snwh** [comment]
This has been fixed.
