### ISSUE TITLE
Good news with GNOME 3.16

### ISSUE THREAD

**Issue by matteosecli** [snwh/paper-gtk-theme#74]
This is not an issue, I just want to report very good news about window decorations in the new development version of GNOME.
I'm testing your theme on a VM with Ubuntu GNOME 15.04 and the GNOME-staging ppa enabled to get the latest version. Up to 3.14 windows without CSD were pretty inconsistent with the overall look of the theme (just take a look at gnome-terminal or firefox): smaller header bars, different on-mouse-over shadows, ...
It was not so evident in Adwaita, but it looked like a punch in the eye for Paper.
Things in 3.16 have finally changed, since server-side decorations have the same style as client-side decorations. A clear example and better explanation of what I mean in this blog (http://blogs.gnome.org/fmuellner/2015/01/30/a-small-note-on-window-decorations/).
To experience the improvement, I've just upgraded to GNOME 3.15 from the GNOME-staging ppa and the result was AMAZING!
Now gnome-terminal looks really nice and all the other apps without CSD have a consistent look.
I've taken a screenshot of what the theme looks like with 3.15 (on the terminal you can see the on-mouse-over close button look, that now matches the one used in CSD apps).
![schermata da 2015-02-12 13-52-16](https://cloud.githubusercontent.com/assets/4618521/6167770/1e057212-b2bf-11e4-91de-9ec16319ffc4.png)
I suggest to point out the improvements with the new version in the README file or on the website. :)

**Comment by snwh** [comment]
Actually, most of Paper was developed on & with 3.16.

**Comment by Polochamps** [comment]
@snwh 
Besides the bug I filed, I just wanted to say thanks to you buddy for this very wonderful theme!

**Comment by tthanh** [comment]
@snwh Thank you for a beautiful theme. I'll try this theme if I reinstall fedora next time. But I still hate big header bar of gnome, waste a lot of px

**Comment by snwh** [comment]
@tthanh that's a misconception. The header bars take up the least space ever on GNOME (or any desktop). http://blogs.gnome.org/aday/2014/08/27/gnome-design-saving-you-space-since-2009-or-so/

**Comment by tthanh** [comment]
@snwh I read that link but I think it still waste px when gnome drop global menu like gnome 2. I'm using ubuntu now because unity menu, save a lot of px, no need header bar for window buttons.

**Comment by snwh** [comment]
Perhaps, but in many cases the header bar has more function than just housing the window controls & title. Rather: should have more function.

**Comment by tthanh** [comment]
I used fews IDE and java app so unity globalmenu help me a lots :smile: Btw, still thank you for greate theme. Ubuntu 15.04 with gtk 3.14 release soon, I can try this theme more :+1:
