### ISSUE TITLE
Theme not properly applied on xfce4/Crouton

### ISSUE THREAD

**Issue by viki53** [snwh/paper-gtk-theme#75]
Hi,

I have a Chromebook on which I installed crouton to get a full Ubuntu with xfce 4.10, but the default theme didn't stick so yesterday I tried installing Paper and the icon theme.

But since I'm kind of a newbie with xfce and Linux customization (I usually use it on servers) I guess I did something wrong or some elements are missing.

Anymay, this is the result I get when I apply the theme:

![screenshot - 15022015 - 12 20 59](https://cloud.githubusercontent.com/assets/1763364/6203078/c5a31290-b50d-11e4-8ec8-f6e940468f01.png)

Do you have any idea what might have gone wrong?

If you need any information just let me know.

Thanks!

**Comment by Defman21** [comment]
IIIRC you can change window decorators in `Preferences - Window manager`but not in `Preferences - Appearance`.

**Comment by viki53** [comment]
Ok, that's kinda better. Thanks!

![screenshot - 15022015 - 13 09 06](https://cloud.githubusercontent.com/assets/1763364/6203185/e369cb9c-b513-11e4-93dc-8250dcb9ada7.png)

Any idea how I can make it look more like the official screenshot (more colors, more space, no glossy effect in the panels, etc)?.

![](http://snwh.org/resources/img/bitmaps/paper-screenshot.png)

**Comment by Defman21** [comment]
Probably change xfce to gnome. I just added basic support for XFCE and nothing more.

**Comment by viki53** [comment]
Ok. Gnome may be too heavy for a Chromebook, so it'll wait... 

Thanks!

**Comment by snwh** [comment]
Yes, the screenshot is GNOME
