### ISSUE TITLE
Text missing from menu button Firefox

### ISSUE THREAD

**Issue by region51** [snwh/paper-gtk-theme#78]
![2015-02-17 17 07 22](https://cloud.githubusercontent.com/assets/10940138/6229336/9f15c6d4-b6c7-11e4-963a-b8ba3bdf0da6.png)
Fedora 21, Gnome 3.14.2

**Comment by axel-sommerfeldt** [comment]
No problem here (Fedora 21 w/ Gnome 3.14.3). Have you tried installing the Firefox AddOn "GNOME3"? Url: https://addons.mozilla.org/de/firefox/addon/adwaita/

**Comment by region51** [comment]
same
![2015-02-18 12 04 59](https://cloud.githubusercontent.com/assets/10940138/6244671/6f28edb6-b767-11e4-819d-eea48804345e.png)
Distro: Fedora release 21 (Twenty One)
Desktop: Gnome 3.14.3

**Comment by region51** [comment]
Well, any ideas?
