### ISSUE TITLE
Some bugs on Ubuntu 14.10 with unity

### ISSUE THREAD

**Issue by throrin19** [snwh/paper-gtk-theme#79]
Hi, after set your theme in ubuntu 14.10 with unity, i have this bug with ubuntu tweak tools : 

Before
![capture du 2015-02-18 11 20 15](https://cloud.githubusercontent.com/assets/1394778/6245613/cd9a10c0-b760-11e4-8de9-7e5dc4636d8a.png)

After
![capture du 2015-02-18 11 20 46](https://cloud.githubusercontent.com/assets/1394778/6245617/d3b76246-b760-11e4-8eee-197c127a3f78.png)

And this is the appearance of hover on topbar buttons on admin pannel : 
![capture du 2015-02-18 11 23 27](https://cloud.githubusercontent.com/assets/1394778/6245663/2cccb034-b761-11e4-80d3-065af0aa2a47.png)

**Comment by abielzuliom** [comment]
Excuse me, but what theme is that in before screenshot? @throrin19

**Comment by throrin19** [comment]
I use [Alpsemite_Light](http://picusricer.deviantart.com/art/Alpsemite-Unity-Theme-v1-20-458520513)
