### ISSUE TITLE
Rythmbox Add Music issue

### ISSUE THREAD

**Issue by mikebell** [snwh/paper-gtk-theme#81]
![](http://i.imgur.com/qoFhkAy.png)

File>Add Music

**Comment by region51** [comment]
selected normal
![2015-03-02 14 52 10](https://cloud.githubusercontent.com/assets/10940138/6440449/06753dde-c0ee-11e4-87bf-24f8df502ff9.png)
![2015-03-02 14 52 16](https://cloud.githubusercontent.com/assets/10940138/6440450/0e0342c6-c0ee-11e4-8c30-00f4ed6d7b9d.png)
unfocus
![2015-03-02 15 02 55](https://cloud.githubusercontent.com/assets/10940138/6440454/14042820-c0ee-11e4-8a49-9db5914b0686.png)

and how to remove the white stripes titlebar?

**Comment by snwh** [comment]
Still open? It appears to be fixed.
