### ISSUE TITLE
Same color in all windows + Different toolbar In GNOME  

### ISSUE THREAD

**Issue by Rishishukla6** [snwh/paper-gtk-theme#83]
I have installed gnome desktop environment along side Ubuntu 14.10 . Going through closed issues i found out that it should work on gnome but i have all the windows with gray color and  the toolbar is not getting changed as expected (back ,forward ,minimize, maximize option are different from the image shown ).

EXPECTED 
![paper-screenshot](https://cloud.githubusercontent.com/assets/10980039/6322065/c745713a-bb32-11e4-80c3-0799dc1d9aef.png)

ON MY SYSTEM 
![screenshot from 2015-02-23 08 04 41](https://cloud.githubusercontent.com/assets/10980039/6322077/1d2d974e-bb33-11e4-8c87-b48d64be97ac.png)

let me know how to solve this issue. Thanks !

**Comment by snwh** [comment]
Well, what distro or version of GNOME are you running?

**Comment by Rishishukla6** [comment]
Hey!! thanks for quick reply !! :) i have installed gnome desktop environment along side Ubuntu 14.04 which is currently at version 3.12. (I'm quite new to Linux so here I'm also attaching tutorial using which i installed gnome , if in case provided information is insufficient)

 http://itsfoss.com/how-to-install-gnome-in-ubuntu-14-04/ )

**Comment by Daisukiookami** [comment]
Hello,
i have exactly the same issue in Linux Mint 17.1 with Cinnamon.

If you found a solution i'm interested also.

Thanks.

**Comment by snwh** [comment]
FYI the effect in the screenshot is only possible with window managers/ desktop environments/ apps that support the gtk 3.14+ headerbars. So far, that's vanilla GNOME.

**Comment by Rishishukla6** [comment]
Can you please post step by command line tutorials or steps to install this team properly along with the steps to install LATEST GTK . My system is up to date but even after that it's not getting installed properly. (I know I'm asking for too much but doing so is going to help a lot of guys who are facing problem).

**Comment by dpocina** [comment]
@Rishishukla6: Ubuntu always ships an old version of gnome. To get to 3.14 you are going to have to add a couple of PPAs

https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3
https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging

I personally use fedora, so I'm not sure how stable is that going to be.

**Comment by Rishishukla6** [comment]
Last time when I installed gnome 13.14 on Ubuntu 14.10 my system crashed and I had to reinstall everything. I'm trying again.lets see what happens.

**Comment by Rishishukla6** [comment]
Finally i managed to get different color for toolbar !! 

![screenshot from 2015-02-24 01 17 27](https://cloud.githubusercontent.com/assets/10980039/6335766/c6919070-bbc3-11e4-8018-7cea631fc7e4.png)


now i'm left with only with two issues
1) The maximize , minimize and close buttons are at right and they are appearing in different icons for different buttons (for some they are appearing like the one shown in expected image and for some they are appearing like the one shown in newly posted above screenshot ). Is it a bug in theme or i'm doing something wrong ?

2) The battery indicator doesn't changes with increase or decrease in power level available. (here  is the screenshot with current icon and power level of my system ). how to solve this issues ?
![screenshot from 2015-02-24 01 32 13](https://cloud.githubusercontent.com/assets/10980039/6335977/7c639a1e-bbc5-11e4-98d8-be9fb1abeffc.png)

**Comment by snwh** [comment]
@Rishishukla6 those last two issues are dependent on whichever icon theme you choose to you.

**Comment by libook** [comment]
@Rishishukla6 There is a setting in tweak tools called "Global Dark theme".  Maybe the problem is it.

**Comment by Rishishukla6** [comment]
no i guess its NUMIX circle icon theme ! PAPER icon themes lack quite a lot of basic icons . Sam please update the paper icons and if possible please varieties to user to chose from (like circle , rectangle icon ).

**Comment by snwh** [comment]
@Rishishukla6 the Paper icons are **pre-alpha** and will **not** have varieties.

**Comment by clauseggers** [comment]
I have this issue too. I’m running the Ubuntu GNOME distro, and I have updated Gnome to 3.14.4 from the Gnome3-Team source linked above, but still I’m getting all grey toolbars. Ideas?

**Comment by nicocarolo** [comment]
@Rishishukla6 sorry, i have the same problem, can you tell me how you solve it? thanks

**Comment by Rishishukla6** [comment]
You have to update your gtk to the latest version. Doing so will solve your problem.

**Comment by pandyatama17** [comment]
@Rishishukla6 sorry, you mean upgrading the gnome?

**Comment by thebarz** [comment]
Actually I want the dark color scheme

**Comment by ZuluagaSD** [comment]
@Rishishukla6 how did you got the different colors to work?

**Comment by Rishishukla6** [comment]
I updated my GTK to the latest version.

**Comment by Rishishukla6** [comment]
@pandyatama17 Sorry for a very late reply. No, I meant, I updated my GTK to the latest release.
