### ISSUE TITLE
Improvements for ElementaryOS 0.3

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-gtk-theme#84]
hello,
i would like you to fix this on elementary os 0.3 beta 2

on settings
![capture du 2015-02-23 21 17 50](https://cloud.githubusercontent.com/assets/7660997/6336454/05c03a74-bba3-11e4-9c5c-c330b45ed5a5.png)
![capture du 2015-02-23 21 18 10](https://cloud.githubusercontent.com/assets/7660997/6336457/05fbd61a-bba3-11e4-8952-d0f7f793fe96.png)
notifications and stuff (elemntary style)
![capture du 2015-02-23 21 20 20](https://cloud.githubusercontent.com/assets/7660997/6336455/05fb2c56-bba3-11e4-818d-daae5832dd4d.png)
![capture du 2015-02-23 21 28 32](https://cloud.githubusercontent.com/assets/7660997/6336456/05fb63f6-bba3-11e4-8fbf-0d84fa13783c.png)

**Comment by vlag24** [comment]
hello, same os and same issues ;) hope to find a solution...

**Comment by bil-elmoussaoui** [comment]
The second have been fixed, for the rest i hope to see an update soon ;)

**Comment by bil-elmoussaoui** [comment]
@snwh the two last bugs has not been fixed yet
