### ISSUE TITLE
how to change the size of icons in the system tray.

### ISSUE THREAD

**Issue by region51** [snwh/paper-gtk-theme#85]
I use the extension TopIcons https://extensions.gnome.org/extension/495/topicons/
Default
![2015-02-25 19 19 35](https://cloud.githubusercontent.com/assets/10940138/6374818/5faf5614-bd24-11e4-9943-db907b428e4a.png)
Paper
![2015-02-25 18 46 36](https://cloud.githubusercontent.com/assets/10940138/6374831/6c46d442-bd24-11e4-8788-dfdec7305d21.png)
Distro: Fedora release 21 (Twenty One)
Desktop: Gnome 3.14.3
any ideas?

**Comment by snwh** [comment]
I've no clue.

**Comment by region51** [comment]
the problem is solved. change the height: 2em;

#panel {
    background-color: rgba(30, 39, 43, 1.0);
    font-weight: normal;
    color: #9FB0B9;
    height: 1.86em;
}

**Comment by snwh** [comment]
That changes the height of the panel; I'm not going to do that.

**Comment by region51** [comment]
the problem is not in your theme
issue https://github.com/mjnaderi/TopTray/issues/1
I'm sorry
