### ISSUE TITLE
where information?

### ISSUE THREAD

**Issue by region51** [snwh/paper-gtk-theme#87]
![2015-02-26-185518_1280x1024_scrot](https://cloud.githubusercontent.com/assets/10940138/6395492/9096c058-bde9-11e4-8961-19527b36a12d.png)

information on a light background appears on the click of a mouse.

Distro: Fedora release 21 (Twenty One)
Desktop: Gnome 3.14.3

**Comment by axel-sommerfeldt** [comment]
Same happens in other Gnome applications like Calc, Software Center, Baobab, ...

**Comment by region51** [comment]
Gedit,Transsmision,Rhythmbox,Gnome-Tweak-Tool and..............................................................................................................................................................................................................................................................................................................................................

**Comment by snwh** [comment]
"Fix committed again"

**Comment by region51** [comment]
@snwh ,Thank you very much, the problem is solved

**Comment by axel-sommerfeldt** [comment]
Just installed a8b3e6d017 and I confirm that this fixes this issue for me. https://github.com/snwh/paper-gtk-theme/issues/67 is also fixed by that commit.

Thanks a lot!
