### ISSUE TITLE
Some little problems...

### ISSUE THREAD

**Issue by region51** [snwh/paper-gtk-theme#91]
hold down the mouse
![2015-02-28 18 33 54](https://cloud.githubusercontent.com/assets/10940138/6426747/dcf421f6-bf7a-11e4-9fbe-24f7632061d4.png)
black is not really beautiful
![2015-02-28 18 34 13](https://cloud.githubusercontent.com/assets/10940138/6426748/e2e2fa10-bf7a-11e4-850c-fbd48a6bd835.png)

**Comment by snwh** [comment]
Similar to #49
