### ISSUE TITLE
Rythmbox ....

### ISSUE THREAD

**Issue by region51** [snwh/paper-gtk-theme#92]
selected normal
![1](https://cloud.githubusercontent.com/assets/10940138/6444646/02362392-c110-11e4-9c17-fd470fba9bcf.png)
no normal
![2](https://cloud.githubusercontent.com/assets/10940138/6444648/07d974ca-c110-11e4-853e-e781475e25bf.png)
unfocused window
![3](https://cloud.githubusercontent.com/assets/10940138/6444656/0f33f7e0-c110-11e4-9067-619a35889424.png)

**Comment by snwh** [comment]
Rhythmbox is a non standard mishmash of GTK elements, it's not going to look perfect.

**Comment by region51** [comment]
So Much Better
![2015-03-09 13 16 08](https://cloud.githubusercontent.com/assets/10940138/6553211/6bee03fa-c65f-11e4-8565-0269539470a4.png)
