### ISSUE TITLE
Unfocused Chrome Uses @wm_color For Frame

### ISSUE THREAD

**Issue by rockon999** [snwh/paper-gtk-theme#93]
Using Paper/gtk-2.0/Apps/chrome.rc with System Title Bar & Borders the following happens:

![screenshot from 2015-03-07 14 06 57](https://cloud.githubusercontent.com/assets/2943271/6543087/57980ba4-c4d3-11e4-9b45-00256d77f109.png)

Inactive Frame Color Should Be:
`ChromeGtkFrame::inactive-frame-color = "#454D50"`

I also experience a similar issue with Incognito (the title bar doesn't match chrome)... but I am unsure of how you would fix this (besides making it the same color as normal chrome windows)

**Comment by snwh** [comment]
Chrome is still GTK2, it doesn't follow the :backdrop state of the GTK3 window managers, not much I can do there.

**Comment by rockon999** [comment]
... But Chrome provides an inactive setting. It may not be the correct way to do it, but visually it would correct the theme.

**Comment by snwh** [comment]
Inactive is the  state of the other tabs that aren't the active tabs.

**Comment by rockon999** [comment]
inactive-frame-color controls the color of the grey behind the tabs while the window is unfocused. I set it to the correct value, and it works just fine.

**Comment by snwh** [comment]
I stand corrected, I was testing without ""

**Comment by rockon999** [comment]
Thanks!
