### ISSUE TITLE
Weird dotted border

### ISSUE THREAD

**Issue by rekuen** [snwh/paper-gtk-theme#98]
I've notice with the last update, a weird dotted border, is really annoying, is this supposed to be like this?
![captura de pantalla de 2015-03-09 15 07 43](https://cloud.githubusercontent.com/assets/2090383/6556489/22a469aa-c66e-11e4-8f31-9d82de25c737.png)
Ubuntu GNOME 14.04
GNOME Shell 3.10.4

**Comment by region51** [comment]
it's ok
![2015-03-09 17 54 44](https://cloud.githubusercontent.com/assets/10940138/6557412/c865ab4e-c685-11e4-866c-409cd46da970.png)
Distro: Fedora release 21 (Twenty One)
Desktop: Gnome 3.14.3

**Comment by rekuen** [comment]
Maybe has something to be with my GNOME version being 3.10?

**Comment by Jenjen1324** [comment]
Same issue on Ubuntu Gnome 14.10
Gnome: 3.10

**Comment by dpocina** [comment]
@rekuen & @Jenjen1324 
Take a look to issue #74

@snwh is developing this theme for 3.16
That means that there is some weirdness even for 3.14 and support is going to get worse the further you go down in the version number  ;)

**Comment by rekuen** [comment]
So no support for those like me that prefer to stay in the LTS? I supposed is a pain in the ass to maintain different branches... I will take a look and try to modify it to support 3.10 then.

Thanks.

**Comment by snwh** [comment]
It should be fixed.

**Comment by rekuen** [comment]
Thanks @snwh, latest update fixed it, the menu with the cog icon remains the same, just changing the font color should fix it but it seems that is no longer present on 3.16, any ideas of how it is called in the css? In spanish says "Opciones de Ubicación" , Location Options I supposed is the translation.

Thanks again.

**Comment by rekuen** [comment]
I took a picture with my phone camera to show you the issue as I can't take a screenshot from gnome or the menu won't appear.

Sorry for the quality, is entire white, unless the mouse is over you can't read anything from that menu on the right.

![gnome_menu_white](https://cloud.githubusercontent.com/assets/2090383/6593165/0ee9fac4-c7d6-11e4-8bd8-50b44d8d5039.jpg)
